ballerina-platform/module-ballerina-graphql

- .gitignore
- graphql-ballerina/common_utils.bal
- graphql-ballerina/constants.bal
- graphql-ballerina/modules/graphql/resources/Client_functions.json
- graphql-ballerina/records.bal
- graphql-ballerina/tests/09_resources_returning_union_types.bal
- graphql-ballerina/tests/expected_values.bal
- graphql-ballerina/validator_visitor.bal
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/Engine.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/IntrospectionUtils.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/Utils.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/schema/SchemaField.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/schema/SchemaType.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/schema/TypeKind.java
With this PR, the Ballerina GraphQL resources can return union types (with `error` type). 
This means the following resource function is allowed:
```ballerina
resource function get profile() returns string|error {
}
```
But the following is not allowed, since the union is only allowed with the error type.
```ballerina
resource function get id() returns int|string{
}
```
Fixes: [#762](https://github.com/ballerina-platform/ballerina-standard-library/issues/762)
> Support Resource Functions Returning Union with Error Type

- graphql-ballerina/Ballerina.toml
- graphql-ballerina/build.gradle
- graphql-ballerina/constants.bal
- graphql-ballerina/engine.bal
- graphql-ballerina/engine_utils.bal
- graphql-ballerina/executor_visitor.bal
- graphql-ballerina/records.bal
- graphql-ballerina/tests/10_resources_returning_arrays.bal
- graphql-ballerina/tests/11_introspection_queries.bal
- graphql-ballerina/tests/records.bal
- graphql-ballerina/tests/values.bal
- graphql-ballerina/validator_visitor.bal
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/Engine.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/EngineUtils.java
With this PR, the GraphQL engine is able to respond introspection queries on the schema types.
Although it still does not support any other introspection query. This is tracked by [#832](https://github.com/ballerina-platform/ballerina-standard-library/issues/832)
Fixes: [#831](https://github.com/ballerina-platform/ballerina-standard-library/issues/831)
Fixes: [#697](https://github.com/ballerina-platform/ballerina-standard-library/issues/697)
> Add Introspection Support for GraphQL Schema

- graphql-ballerina/engine.bal
- graphql-ballerina/executor_visitor.bal
- graphql-ballerina/http_service.bal
- graphql-ballerina/modules/parser/tests/to_record_visitor.bal
- graphql-ballerina/records.bal
- graphql-ballerina/validator_visitor.bal
Some of the types defined in GraphQL module shouldn't be public, even though some of them are marked as public in the initial implementation. With this PR, those types are marked as non-public.
Fixes: [#871](https://github.com/ballerina-platform/ballerina-standard-library/issues/871)
> Make suitable types non-public

- graphql-ballerina/listener.bal
- graphql-ballerina/records.bal
- graphql-ballerina/tests/12_listener_configurations_test.bal
With this PR, developers can pass the configurations related to http listener, when creating a graphql listener without using the http listener configs.
```ballerina
graphql:ListenerConfiguration configs = {
timeoutInMillis: 5000
// We can add any configuration related to the http listener here
};
service /graphql on new graphql:Listener(9090, configs) {
// resources
}
```
Added a simple test to check whether the configs are passed properly, since all the other configs acts same.
Fixes: [#934](https://github.com/ballerina-platform/ballerina-standard-library/issues/934)
> Add HTTP Listener Configs to the GraphQL Listener

- graphql-ballerina/engine.bal
- graphql-ballerina/listener.bal
- graphql-ballerina/modules/parser/operation_node.bal
- graphql-ballerina/modules/parser/parser.bal
- graphql-ballerina/records.bal
- graphql-ballerina/tests/12_listener_configurations_test.bal
- graphql-ballerina/validator_visitor.bal
GraphQL endpoints can be secured in many ways. One of the popular method is to limit the depth of an accepted query before executing it. This way, we can avoid queries which may be too deep.
With this PR, a new configuration `maxQueryDepth` is introduced to meet this requirement. The `graphql:ListenerConfiguration` now have a `maxQueryDepth` field. We can provide any integer value greater than zero to this field. Then when a document is received, at the validation phase, the query will be validated for its depth and if the depth of the query exceeds the provided maximum depth, the execution will not occur.
Consider the following example, where there is a cyclic reference between the Book and the Author records.
```ballerina
graphql:ListenerConfiguration configs = …
```
> Add max query depth validation for graphql queries

- graphql-ballerina/build.gradle
> Renames the extension of the package distribution file from balo to bala 
> Fixes ballerina-platform/ballerina-lang#28476
> Change ballerina archive extension to bala

- graphql-ballerina/annotation_processor.bal
- graphql-ballerina/annotations.bal
- graphql-ballerina/engine.bal
- graphql-ballerina/errors.bal
- graphql-ballerina/listener.bal
- graphql-ballerina/records.bal
- graphql-ballerina/tests/12_listener_configurations_test.bal
With this PR, the `maxQueryDepth` config will be moved to the service annotation, instead of the `ListenerConfiguration`. 
Now when creating a service, the max query depth can be provided as follows:
```ballerina
listener graphql:Listener graphqlListener = new(9090);
@graphql:ServiceConfiguration {
maxQueryDepth: 2
}
service /graphql on depthLimitListener {
isolated resource function get greet() returns string {
return "Hello";
}
}
```
The `maxQueryDepth` should be an integer greater than `1`. If the provided value is lesser than `1`, a `ListenerError` will be thrown at the runtime.
Related PR(s): #66 
Fixes: [#938](https://github.com/ballerina-platform/ballerina-standard-library/issues/938)
> Move the maxQueryDepth Configuration to Service Level

- .github/workflows/build-master.yml
- .github/workflows/pull-request.yml
- build.gradle
- graphql-ballerina/build.gradle
- graphql-native/build.gradle
- With this change only testerina generated XML will be used for the codecov coverage report
> Remove Jacoco XML Report Generation Gradle Tasks

- graphql-ballerina/build.gradle
Instead of including all the classes in the test report, this will include only the classes needed to generate the exec file. The files needed are:
- Native code (Java) using `io.ballerina.stdlib.graphql.*`
- Ballerina Code using `ballerina.*`
We can provide a list of paths to include as a list, separated by `:`.
> Filter only package native classes for test coverage report

- graphql-ballerina/engine_utils.bal
- graphql-ballerina/executor_visitor.bal
- graphql-ballerina/tests/08_resources_returning_union_types.bal
- graphql-ballerina/tests/12_hierarchical_resource_paths.bal
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/Engine.java
$Subject
With this PR, resource functions with optional return values are supported. 
```ballerina
service /graphql on new graphql:Listener(9090) {
resource function get profile(int id) returns Person|error? {
// ...
}
}
```
Fixes: [#912](https://github.com/ballerina-platform/ballerina-standard-library/issues/912)
> Add Support to Return Optional type from Resource Functions

- graphql-ballerina/tests/13_resources_returninng_tables.bal
- graphql-ballerina/tests/records.bal
- graphql-ballerina/tests/values.bal
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/Engine.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/schema/tree/SchemaGenerator.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/schema/tree/SchemaTreeGenerator.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/schema/tree/TypeTreeGenerator.java
With this PR, the Ballerina GraphQL services can return `table` types from a GraphQL service resource function. The GraphQL TypeKind of the resource function will be `LIST`, and it will return the results as a JSON array.
Each field of the table can be queried separately and querying for the whole table will return an error.
Fixes: [#648](https://github.com/ballerina-platform/ballerina-standard-library/issues/648)
```ballerina
public type Employee record {|
int id;
string name;
decimal salary;
|};
public type EmployeeTable table<Employee> key(id);
service graphql:Service /graphql on new graphql:Listener(9090) {
isolated resource function get employees() returns EmployeeTable {
return table [
{ id: 1, name: "John Doe", salary: 1000.00 },
{ id: 2, name: "Jane Doe", …
```
> Add Support for Ballerina Table Types

- changelog.md
- graphql-ballerina/records.bal
- graphql-ballerina/tests/08_resources_returning_union_types.bal
- graphql-ballerina/tests/15_enums.bal
- graphql-ballerina/tests/expected_values.bal
- graphql-ballerina/tests/records.bal
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/EngineUtils.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/tree/SchemaGenerator.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/tree/SchemaTreeGenerator.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/tree/TypeTreeGenerator.java
Add support for enums in Ballerina GraphQL schemas.
Fixes: [#1000](https://github.com/ballerina-platform/ballerina-standard-library/issues/1000)
The following is now allowed:
```ballerina
service graphql:Service /grraphql on new graphql:Listener(9090) {
isolated resource function get day(int number) returns Weekday|error {
if (number < 1 || number > 7) {
return error("Invalid number");
} else if (number == 1) {
return MONDAY;
} else if (number == 2) {
return TUESDAY;
} else if (number == 3) {
return WEDNESDAY;
} else if (number == 4) {
return THURSDAY;
} else if (number == 5) {
return FRIDAY;
} else if (number == 6) {
return SATURDAY;
} else {
return SUNDAY;
}
}
}
public enum Weekday {
SUNDAY,
MONDAY,
TUESDAY,
WEDNESDAY,
THURSDAY,
FRIDAY,
SATURDAY
}
```
This can …
> Support Enum Type in GraphQL Schema

- .github/workflows/central-publish.yml
- README.md
- graphql-ballerina/build.gradle
Move ballerina build, test and publish tasks under a single task to avoid running the update and revert toml file tasks multiple times.
Part of [#1247](https://github.com/ballerina-platform/ballerina-standard-library/issues/1247)
> Move ballerina Build, Test and Publishing Into a Single Task

- changelog.md
- graphql-ballerina/common_utils.bal
- graphql-ballerina/constants.bal
- graphql-ballerina/records.bal
- graphql-ballerina/tests/08_resources_returning_union_types.bal
- graphql-ballerina/tests/15_enums.bal
- graphql-ballerina/tests/expected_values.bal
- graphql-ballerina/validator_visitor.bal
- graphql-compiler-plugin-tests/build.gradle
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/CallableUnitCallback.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/EngineUtils.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/IntrospectionUtils.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/SchemaType.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/TypeKind.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/tree/Node.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/tree/SchemaGenerator.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/tree/SchemaTreeGenerator.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/tree/TypeTreeGenerator.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/tree/Utils.java
Support Union Types in GraphQL Schemas.
With this PR, the Ballerina GraphQL services can have union types as fields.
Fixes: [#1001](https://github.com/ballerina-platform/ballerina-standard-library/issues/1001)
Following Ballerina code is now valid:
```ballerina
type Student record {
int id;
string name;
string[] subjects;
};
type Teacher record {
int id;
string name;
string subject;
float salary;
};
type Person Student|Teacher;
service graphql:Service /graphql on new graphql:Listener(9090) {
resource function get profile(int id) returns Person {
// return a Student or Teacher
}
}
```
To query this the following query can be used:
```
query {
profile(id: 4) {
...studentFragment
...teacherFragment
}
}
fragment studentFragment on Student {
id
name
}
fragment …
```
> Add Support to Union Types in GraphQL Services

- changelog.md
- graphql-ballerina/engine_utils.bal
- graphql-ballerina/executor_visitor.bal
- graphql-ballerina/tests/09_resources_returning_arrays.bal
- graphql-ballerina/tests/10_introspection_queries.bal
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/CallableUnitCallback.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java
Fixes: [#1250](https://github.com/ballerina-platform/ballerina-standard-library/issues/1250) 
N/A
> Fix Hanging the Service when Returning Array

- changelog.md
- graphql-compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/CompilerPluginTest.java
- graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_5/Ballerina.toml
- graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_5/service.bal
- graphql-compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/GraphqlFunctionValidator.java
- graphql-compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/PluginConstants.java
Support Enum Type in GraphQL Resource Function Input Params.
```
enum Color {
RED,
GREEN,
BLUE
}
service graphql:Service on new graphql:Listener(4000) {
isolated resource function get color(Color color) returns Color {
return RED;
}
} 
```
> Add Support to Enum Type in Resource Function Params

- changelog.md
- graphql-ballerina/engine.bal
- graphql-ballerina/executor_visitor.bal
- graphql-ballerina/records.bal
- graphql-ballerina/tests/04_resource_functions_with_input_parameters.bal
- graphql-ballerina/tests/06_errors_test.bal
- graphql-ballerina/tests/10_introspection_queries.bal
- graphql-ballerina/tests/expected_values.bal
- graphql-ballerina/validator_visitor.bal
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/FieldFinder.java
- graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/SchemaRecordGenerator.java
Fixing bugs in input parameter validation.
Fixes: [#1251](https://github.com/ballerina-platform/ballerina-standard-library/issues/1251)
Fixes: [#1269](https://github.com/ballerina-platform/ballerina-standard-library/issues/1269)
Fixes: [#1266](https://github.com/ballerina-platform/ballerina-standard-library/issues/1266)
N/A
> Input parameter validation

- changelog.md
- graphql-ballerina/common_utils.bal
- graphql-ballerina/records.bal
- graphql-ballerina/tests/10_introspection_queries.bal
- graphql-ballerina/tests/14_fragments.bal
- graphql-ballerina/tests/expected_values.bal
- graphql-ballerina/validator_visitor.bal
$Subject
Fixes: [#1329](https://github.com/ballerina-platform/ballerina-standard-library/issues/1329)
> Add Missing Fields of Schema Related Records

- changelog.md
- graphql-compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/CompilerPluginTest.java
- graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_11/Ballerina.toml
- graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_11/service.bal
- graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_7/Ballerina.toml
- graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_7/service.bal
- graphql-compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/GraphqlFunctionValidator.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1339
$title
> Update input param validation logic

- changelog.md
- graphql-ballerina/build.gradle
- graphql-ballerina/listener.bal
- graphql-ballerina/tests/11_listener_configurations_test.bal
- graphql-compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/CompilerPluginTest.java
- graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_16/Ballerina.toml
- graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_16/service.bal
- graphql-compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/GraphqlListenerValidator.java
With this PR, instead of passing the` graphql:ListnerConfiguration` record, the input parameters can be passed separately as named parameters. 
Fixes: [#998](https://github.com/ballerina-platform/ballerina-standard-library/issues/998)
```ballerina
service graphql:Service on new graphql:Listener(9090, timeout = 5, host = "0.0.0.0") {
// ....
}
```
> Use Included Record Parameters in Listener Init Function

- .github/workflows/pull-request.yml
- ballerina/modules/parser/tests/lexer_tests.bal
- ballerina/modules/parser/tests/parser_tests.bal
- ballerina/modules/parser/tests/resources/documents/multiple_anonymous_operations.txt
- ballerina/modules/parser/tests/resources/documents/multiple_operations_with_same_name.txt
- ballerina/modules/parser/tests/resources/documents/named_operation_with_anonymous_operation.txt
- ballerina/modules/parser/tests/resources/documents/named_operation_with_multiple_anonymous_operations.txt
- ballerina/modules/parser/tests/resources/documents/read_comment_token.txt
- ballerina/modules/parser/tests/resources/documents/three_anonymous_operations.txt
- ballerina/modules/parser/tests/utils.bal
- ballerina/tests/14_fragments.bal
- ballerina/tests/19_distinct_service_unions.bal
- ballerina/tests/resources/documents/invalid_query_with_distinct_service_unions.txt
- ballerina/tests/resources/documents/unknown_fragment.txt
- gradle.properties
$Subject
In Windows tests, the expected line numbers are incorrect compared to the actual ones when we use `string` literal inside ballerina code as the document. The reason is that the end of line character acts differently in *nix systems and the Windows systems. Therefore, the GraphQL documents are moved to a separate text file and read when running the tests.
Fixes: [#835](https://github.com/ballerina-platform/ballerina-standard-library/issues/835)
N/A
> Enable windows tests

- build.gradle
Currently, the release build will not build the compiler plugin tests and example tests, which is problematic. With this PR, the release build will first build all the submodules before committing the release versions.
N/A
> Update Release Task Dependencies

- ballerina/Dependencies.toml
- ballerina/context.bal
- ballerina/http_service.bal
- ballerina/listener_utils.bal
- ballerina/tests/27_context.bal
- ballerina/tests/test_services.bal
- ballerina/types.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_12/service.bal
- examples/snowtooth/Dependencies.toml
The context init function parameters should be ordered as follows as per the convension:
```
isolated function (http:RequestContext requestContext, http:equest request) returns graphql:Context|error {
}
```
Part of [#1906](https://github.com/ballerina-platform/ballerina-standard-library/issues/1906)
> Change the Context Init Parameter Order

- ballerina/Dependencies.toml
- examples/snowtooth/Dependencies.toml
- native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/EngineUtils.java
- native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ResponseGenerator.java
- native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/Utils.java
Currently, when a record type is an intersection type, the type name of that record is retrieved using string manipulation. This was because there was no API to retrieve the type name from an intersection type. With https://github.com/ballerina-platform/ballerina-lang/issues/32215, we can improv this. 
Fixes: [1649](https://github.com/ballerina-platform/ballerina-standard-library/issues/1649)
N/A
> Update Retrieving the Intersection Type Names from Records

- ballerina/listener.bal
- ballerina/listener_utils.bal
- ballerina/tests/01_listener_test.bal
- ballerina/tests/test_services.bal
- ballerina/tests/utils.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ListenerUtils.java
Previously, when the `detach` function of the GraphQL listener is called, no matter which service is passed to detach, the latest attached HTTP service is being detached from the underlying HTTP listener. This causes unexpected results.
This PR will fix this issue, by keeping track the HTTP service related to a particular GraphQL service. 
Fixes: [#2356](https://github.com/ballerina-platform/ballerina-standard-library/issues/2356)
N/A
> Fix service detaching logic in listener

- changelog.md
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/CompilerPluginTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_27/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_27/service.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/Utils.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/validator/FunctionValidator.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/validator/ListenerValidator.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/validator/ServiceAnalyzer.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/validator/ServiceValidator.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/validator/ValidatorUtils.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/validator/errors/CompilationError.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/validator/errors/ErrorCode.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/validator/errors/ErrorMessage.java
- Refactoring the compiler plugin code to match with the compile-time schema generation task. 
- Disallow the path parameters and resource functions without resource path (dotted resources).
Fixes: [#2465](https://github.com/ballerina-platform/ballerina-standard-library/issues/2465)
The following resource functions inside a GraphQL service will cause compilation errors.
Example 1 - Path Parameters:
```ballerina
resource function get profile/[string id]/name() returns string {
return "Walter White";
}
```
Example 2 - Path rest parameters:
```ballerina
resource function get profile/[string ...ids] returns string {
return "Walter White";
}
```
__Example 3 - Dotted resource paths:__
```ballerina
resource function get .() returns int {
return 767;
}
```
> Refactor Compiler Plugin Code and Invalidate Path Parameters

- ballerina/context.bal
- ballerina/tests/27_context.bal
- changelog.md
Fixes: [#2476](https://github.com/ballerina-platform/ballerina-standard-library/issues/2476)
N/A
> Deprecate `context.add` Function and Introduce `context.set` Function

- ballerina/Dependencies.toml
- load-tests/snowtooth/scripts/run.sh
The load tests are failing due to an increase in requests suddenly. This PR will increase the ramp-up time of the load test, therefore the increase of requests will be reduced.
N/A
> Increase Load Test Ramp-up Time

- ballerina/Dependencies.toml
- ballerina/common_utils.bal
- ballerina/tests/26_nullable_values.bal
- ballerina/tests/test_services.bal
- ballerina/validator_visitor.bal
- ballerina/variable_validator.bal
- changelog.md
Fixes: [#2696](https://github.com/ballerina-platform/ballerina-standard-library/issues/2696)
N/A
> Fix Not Allowing to Pass `null` as Variable Input Value

- ballerina/Dependencies.toml
- ballerina/tests/26_nullable_values.bal
- ballerina/tests/33_nullable_inputs.bal
- ballerina/tests/records.bal
- ballerina/tests/resources/documents/non_null_input_for_nullable_list.graphql
- ballerina/tests/resources/documents/non_null_input_for_nullable_record.graphql
- ballerina/tests/resources/documents/non_null_input_for_nullable_record_field.graphql
- ballerina/tests/resources/documents/null_input_for_nullable_record_field.graphql
- ballerina/tests/test_services.bal
- native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ArgumentHandler.java
$Subject
This bug was introduced with #605. Therefore, no released versions are affected by the bug. Therefore, the changelog is not updated. 
Fixes: [#2712](https://github.com/ballerina-platform/ballerina-standard-library/issues/2712)
N/A
> Fix not Allowing `null` Values as Arguments

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/common_utils.bal
- ballerina/errors.bal
- ballerina/graphql_client.bal
- ballerina/modules/parser/records.bal
- ballerina/records.bal
- ballerina/tests/client_test.bal
- ballerina/types.bal
- native/src/main/java/io/ballerina/stdlib/graphql/runtime/client/QueryExecutor.java
Add the generic GraphQL client implementation.
The client supports 2 remote operations.
- executeWithType (Executes a GraphQL query and data binds the GraphQL response to a record with data and extensions. The errors of the GraphQL response are directed in the Ballerina error path.)
For example
```
type GenericResponse record {|
map<json?> extensions?;
record {| anydata...; |}|map<json?> data?;
|};
```
- execute (Executes a GraphQL query and data binds the GraphQL response to a record with data, extensions and errors. The errors of the GraphQL response are directed in the Ballerina target type data binding path.)
For example
```
type GraphQLGenericResponse record {|
map<json?> extensions?;
record {| anydata...; |}|map<json?> data?;
GraphQLError[] errors?;
|};
```
Fixes: …
> Add generic graphql client

- ballerina-tests/tests/04_input_parameters.bal
- ballerina-tests/tests/records.bal
- ballerina-tests/tests/resources/expected_results/deprecated_fields_filtering.json
- ballerina-tests/tests/resources/expected_results/deprecated_fields_filtering_with_variables.json
- ballerina-tests/tests/resources/expected_results/deprecated_fields_introspection.json
- ballerina-tests/tests/resources/expected_results/deprecated_fields_introspection_with_variables.json
- ballerina-tests/tests/resources/expected_results/documentation.json
- ballerina-tests/tests/test_services.bal
- changelog.md
- compiler-plugin-tests/src/test/resources/ballerina_sources/generator_tests/02_record_types/service.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/generator_tests/08_input_scalar_types/service.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GeneratorUtils.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/SchemaGenerator.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/types/Directive.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/types/EnumValue.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/types/Field.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/types/InputValue.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/types/Type.java
- docs/spec/spec.md
When a field name, argument name, or type name has escape characters, the generated schema causes problems. This PR will fix those issues.
Fixes: [#3069](https://github.com/ballerina-platform/ballerina-standard-library/issues/3069)
Fixes: [#3067](https://github.com/ballerina-platform/ballerina-standard-library/issues/3067)
> Fix Escape Character Issues

- ballerina-tests/Ballerina.toml
- ballerina-tests/Dependencies.toml
- ballerina-tests/tests/04_input_parameters.bal
- ballerina-tests/tests/test_services.bal
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- changelog.md
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GeneratorUtils.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/TypeFinder.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/types/Directive.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/types/EnumValue.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/types/Field.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/types/InputValue.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/types/Type.java
- docs/spec/spec.md
- gradle.properties
Fixes: [#3067](https://github.com/ballerina-platform/ballerina-standard-library/issues/3067)
Fixes: [#3069](https://github.com/ballerina-platform/ballerina-standard-library/issues/3069)
These are already been fixed in the master, this is for the patch release.
> Fix Escape Character Issues for Patch Branch

- examples/build.gradle
When the minor (or the major) version is bumped, the examples fail to build locally, due to the `Dependencies.toml` file not updating the GraphQL version. This is not affecting the GitHub workflow builds because we do not commit the Dependencies.toml file for the examples. But this is a pain for the local development environment. Therefore, the clean task is updated to delete the Dependencies.toml file.
> Update Gradle Clean Task to Remove Dependencies.toml from the Examples

- ballerina-tests/tests/11_configurations_test.bal
- ballerina-tests/tests/14_fragments.bal
- ballerina-tests/tests/resources/expected_results/fragment_query_exceeding_max_depth.json
- ballerina-tests/tests/resources/expected_results/fragments_spread_itself.json
- ballerina-tests/tests/resources/expected_results/fragments_with_cycles.json
- ballerina/engine.bal
- ballerina/field_validator_visitor.bal
- ballerina/fragment_cycle_finder_visitor.bal
- ballerina/fragment_validator_visitor.bal
- ballerina/modules/parser/argument_node.bal
- ballerina/modules/parser/fragment_node.bal
- ballerina/modules/parser/operation_node.bal
- ballerina/variable_validator_visitor.bal
- changelog.md
Fixes: [#2848](https://github.com/ballerina-platform/ballerina-standard-library/issues/2848)
> Update validateDocument function to validate the entire document and return all validation errors at once

- docs/spec/spec.md
Currently, due to a limitation on the lang side, the schema generation for a dynamically attached service is limited for the services that are defined in the global scope. This is discussed in the following issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3317#issuecomment-1268171874
Therefore, with this PR, we are updating the spec to reflect the limitation now and park the implementation. We can consider this in the future, may be with some Project API improvements.
> Update the Spec to Reflect Dynamic Service Attaching Issue

- README.md
- ballerina-tests/Dependencies.toml
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- ballerina/Package.md
- build-config/resources/Ballerina.toml
- changelog.md
- docs/spec/spec.md
- gradle.properties
$Subject
- Rearranged the version order in the gradle.properties
Related Issue: [#3463](https://github.com/ballerina-platform/ballerina-standard-library/issues/3463)
> Replace Slack References with Discord and Bump Versions to Prepare for 2201.3.0 Update

- ballerina-tests/Ballerina.toml
- ballerina-tests/Dependencies.toml
- ballerina-tests/tests/07_service_objects.bal
- ballerina-tests/tests/16_maps.bal
- ballerina-tests/tests/36_subscriptions.bal
- ballerina-tests/tests/object_types.bal
- ballerina-tests/tests/records.bal
- ballerina-tests/tests/resources/expected_results/resolver_returning_list_of_nested_service_objects.json
- ballerina-tests/tests/resources/expected_results/resolver_returning_table_of_nested_service_objects.json
- ballerina-tests/tests/test_listeners.bal
- ballerina-tests/tests/test_services.bal
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/engine_utils.bal
- ballerina/response_generator.bal
- changelog.md
Fixes: [#3466](https://github.com/ballerina-platform/ballerina-standard-library/issues/3466)
Fixes: [#3579](https://github.com/ballerina-platform/ballerina-standard-library/issues/3579)
> Fix resolver returning null when record has service objects or map of service objects as its field

- ballerina-tests/tests/01_listener_test.bal
- ballerina-tests/tests/test_listeners.bal
- ballerina-tests/tests/test_services.bal
- ballerina-tests/tests/utils.bal
- ballerina/listener.bal
- changelog.md
Fixes: [#3601](https://github.com/ballerina-platform/ballerina-standard-library/issues/3601)
N/A
> Fix Allow to Attach a Service with Subscription to a Http2 Based Listener

- ballerina-tests/build.gradle
- ballerina-tests/tests/36_subscriptions.bal
- ballerina/websocket_service.bal
- ballerina/websocket_utils.bal
- changelog.md
$Subject
Fixes: [#3661](https://github.com/ballerina-platform/ballerina-standard-library/issues/3661)
> Close the Stream when a Subscription Operation is Completed

- .github/workflows/build-with-bal-test-native.yml
GraphQL tests requires about 6.2GB of memory to build the GraalVM native image. The GitHub runner only have 7GB memory, and, by default, about 80% of that memory (5.8GB) is available for native image builder. In this PR, the maximum Java heap size for native image builder is increased to 7GB.
Fixes : `Build with bal test native` workflow failure due to OOM
Workflow run with this fix : https://github.com/ballerina-platform/module-ballerina-graphql/actions/runs/3581779235
N/A
> Increase Java heap size for native test workflow

- ballerina/client.bal
- docs/spec/spec.md
This PR adds a section to describe when to return `nil` and when to return `error`, and when to combine both.
Fixes: [#3887](https://github.com/ballerina-platform/ballerina-standard-library/issues/3887)
> Add error and nil returning section to the spec

- ballerina-tests/tests/10_introspection_queries.bal
- ballerina-tests/tests/resources/documents/typename_introspection_on_field.graphql
- ballerina-tests/tests/resources/documents/typename_introspection_on_schema_introspection.graphql
- ballerina-tests/tests/resources/documents/typename_introspection_on_type_record.graphql
- ballerina-tests/tests/resources/expected_results/typename_introspection_on_field.json
- ballerina-tests/tests/resources/expected_results/typename_introspection_on_schema_introspection.json
- ballerina-tests/tests/resources/expected_results/typename_introspection_on_type_record.json
- ballerina/introspection_executor.bal
- changelog.md
$Subject
Fixes: [#4038](https://github.com/ballerina-platform/ballerina-standard-library/issues/4038)
N/A
> Fix `__typename` Introspection not Working on Introspection Types

- ballerina-tests/Dependencies.toml
- ballerina-tests/tests/10_introspection_queries.bal
- ballerina-tests/tests/resources/documents/typename_introspection_on_field.graphql
- ballerina-tests/tests/resources/documents/typename_introspection_on_schema_introspection.graphql
- ballerina-tests/tests/resources/documents/typename_introspection_on_type_record.graphql
- ballerina-tests/tests/resources/expected_results/typename_introspection_on_field.json
- ballerina-tests/tests/resources/expected_results/typename_introspection_on_schema_introspection.json
- ballerina-tests/tests/resources/expected_results/typename_introspection_on_type_record.json
- ballerina/Dependencies.toml
- ballerina/introspection_executor.bal
- changelog.md
$Subject
Fixes: [#4038](https://github.com/ballerina-platform/ballerina-standard-library/issues/4038)
N/A
> [2201.3.x] Fix `__typename` Introspection not Working on Introspection Types

- changelog.md
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/ServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/validator_tests/53_non_distinct_interface/service.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/diagnostics/CompilationDiagnostic.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/diagnostics/DiagnosticCode.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/diagnostics/DiagnosticMessage.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/service/validator/ServiceValidator.java
- docs/spec/spec.md
$Subject
Fixes: [#3337](https://github.com/ballerina-platform/ballerina-standard-library/issues/3337)
N/A
> Fix Allowing the use of Non-Distinct Service Objects as GraphQL Interfaces

- ballerina-tests/tests/39_field_object.bal
- ballerina-tests/tests/resources/documents/field_object_parameter_order.graphql
- ballerina-tests/tests/resources/expected_results/complex_introspection_query.json
- ballerina-tests/tests/resources/expected_results/complex_introspection_query_with_other_fields.json
- ballerina-tests/tests/test_services.bal
- native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ArgumentHandler.java
This is to fix the issue where the `graphql:Context` and `graphql:Field` object parameters are not populated properly when they are added after the other parameters. Found this issue when testing with the SwanLake Update 4 RC1. 
An issue was not created because the issue is part of the feature that is intended to ship with this release. This issue hasn't been affected anything.
> Fix context and Field Object Parameter Ordering Issue

- examples/starwars/service.bal
$Subject
We don't need to create the topic manually since the PubSub will create topics automatically.
N/A
> Remove unnecessary init method in the service

- changelog.md
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/ServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/validator_tests/27_invalid_return_types/service.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/service/validator/ServiceValidator.java
Fixes: [#4566](https://github.com/ballerina-platform/ballerina-standard-library/issues/4566)
N/A
> [2201.6.x] Fix Compiler Plugin Failure when Returning an Invalid Intersection Type

- changelog.md
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/ServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/validator_tests/27_invalid_return_types/service.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/service/validator/ServiceValidator.java
Fixes: [#4566](https://github.com/ballerina-platform/ballerina-standard-library/issues/4566)
N/A
> Fix Compiler Plugin Failure when Returning an Invalid Intersection Type

- ballerina-tests/Ballerina.toml
- ballerina-tests/Dependencies.toml
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/client.bal
- changelog.md
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4630
> Deprecate executeWithType API from graphql:Client

- ballerina-tests/Dependencies.toml
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ArgumentHandler.java
> Bump to the next minor version and remove JsonUtils deprecated API 

- changelog.md
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/ServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/validator_tests/76_invalid_empty_record_types/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/validator_tests/76_invalid_empty_record_types/service.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/diagnostics/CompilationDiagnostic.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/diagnostics/DiagnosticCode.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/diagnostics/DiagnosticMessage.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/service/validator/ServiceValidator.java
- docs/spec/spec.md
$Subject
Fixes: [#4224](https://github.com/ballerina-platform/ballerina-standard-library/issues/4724)
N/A
> Fix allowing empty record types as GraphQL object types

- .github/workflows/publish-release.yml
$subject
The publish release [workflow was failing](https://github.com/ballerina-platform/module-ballerina-graphql/actions/runs/6218336398/workflow) with the error `The workflow is not valid. .github/workflows/publish-release.yml (Line: 17, Col: 22): Invalid input, secrets is not defined in the referenced workflow.`
This PR fixes the above
> Fix invalid publish-release workflow

- ballerina-tests/Dependencies.toml
- ballerina/Dependencies.toml
- changelog.md
- commons/src/main/java/io/ballerina/stdlib/graphql/commons/utils/TypeUtils.java
- commons/src/main/java/io/ballerina/stdlib/graphql/commons/utils/Utils.java
- native/src/main/java/io/ballerina/stdlib/graphql/runtime/client/QueryExecutor.java
Fixes: ballerina-platform/ballerina-standard-library#4911.
I am not sure what exactly should be done regarding:
> if there are any, please update the GraphQL version in [GraphQL tools](https://github.com/ballerina-platform/graphql-tools) and [Ballerina dev tools](https://github.com/ballerina-platform/ballerina-dev-tools)
> Make some Java classes proper utilities

- examples/news_alerts/.github/README.md
- examples/simple_github_issue_tracker/.github/README.md
- examples/snowtooth/.github/README.md
- examples/starwars/.github/README.md
This is to show the example markdown file as a README file properly. Since we have different names for the MD file, GitHub does not show them as the README file by default.
> Update symlinks for example readme files

- .gitignore
- ballerina-tests/tests/25_input_objects.bal
- ballerina-tests/tests/resources/documents/input_object_with_unexpected_variable_fields1.graphql
- ballerina-tests/tests/resources/documents/input_object_with_unexpected_variable_fields2.graphql
- ballerina-tests/tests/resources/expected_results/input_object_with_unexpected_variable_fields1.json
- ballerina-tests/tests/resources/expected_results/input_object_with_unexpected_variable_fields2.json
- ballerina/field_validator_visitor.bal
- changelog.md
Fixes: [#7317](https://github.com/ballerina-platform/ballerina-library/issues/7317)
N/A
> [2201.9.x] Fix Service Crashing when Input Object Type Variable Value Includes an Additional Field

- ballerina-tests/graphql-advanced-test-suite/Dependencies.toml
- ballerina-tests/graphql-client-test-suite/Dependencies.toml
- ballerina-tests/graphql-dataloader-test-suite/Dependencies.toml
- ballerina-tests/graphql-interceptor-test-suite/Dependencies.toml
- ballerina-tests/graphql-security-test-suite/Dependencies.toml
- ballerina-tests/graphql-service-test-suite/Dependencies.toml
- ballerina-tests/graphql-service-test-suite/tests/23_input_objects.bal
- ballerina-tests/graphql-service-test-suite/tests/resources/documents/input_object_with_unexpected_variable_fields1.graphql
- ballerina-tests/graphql-service-test-suite/tests/resources/documents/input_object_with_unexpected_variable_fields2.graphql
- ballerina-tests/graphql-service-test-suite/tests/resources/expected_results/input_object_with_unexpected_variable_fields1.json
- ballerina-tests/graphql-service-test-suite/tests/resources/expected_results/input_object_with_unexpected_variable_fields2.json
- ballerina-tests/graphql-subgraph-test-suite/Dependencies.toml
- ballerina-tests/graphql-subscription-test-suite/Dependencies.toml
- ballerina-tests/graphql-test-common/Dependencies.toml
- ballerina/Dependencies.toml
- ballerina/field_validator_visitor.bal
- changelog.md
Fixes: [#7317](https://github.com/ballerina-platform/ballerina-library/issues/7317)
N/A
> Fix Service Crashing when Input Object Type Variable Value Includes an Additional Field

- .github/workflows/build-with-bal-test-graalvm.yml
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/4039
Part of: https://github.com/ballerina-platform/ballerina-library/issues/7384
Part of: https://github.com/ballerina-platform/ballerina-library/issues/3755
N/A
> Fix GraalVM workflow issues

- ballerina-tests/graphql-dataloader-test-suite/tests/01_dataloader_tests.bal
- ballerina-tests/graphql-subscription-test-suite/modules/five/tests/01_subscription_five_tests.bal
- ballerina-tests/graphql-subscription-test-suite/modules/five/tests/02_subscription_with_context.bal
- ballerina-tests/graphql-subscription-test-suite/modules/five/tests/03_subscription_with_constraint.bal
- ballerina-tests/graphql-subscription-test-suite/modules/four/tests/01_subscription_four_tests.bal
- ballerina-tests/graphql-subscription-test-suite/modules/one/tests/01_subscription_tests.bal
- ballerina-tests/graphql-subscription-test-suite/modules/six/tests/01_subscription_six_tests.bal
- ballerina-tests/graphql-subscription-test-suite/modules/six/tests/01_subscription_with_interceptors.bal
- ballerina-tests/graphql-subscription-test-suite/modules/three/tests/01_subscription_three_tests.bal
- ballerina-tests/graphql-subscription-test-suite/modules/two/tests/01_subscription_two_tests.bal
- ballerina/tests/03_subscriptions.bal
Temporarily disabling due to lang build intermittently hanging
Related issue: https://github.com/ballerina-platform/ballerina-library/issues/7030
logs: https://github.com/ballerina-platform/ballerina-lang/actions/runs/12150965444/job/33892381168?pr=43606
> Disable subscription tests

- ballerina-tests/graphql-dataloader-test-suite/Dependencies.toml
- ballerina-tests/graphql-dataloader-test-suite/tests/01_dataloader_tests.bal
- ballerina-tests/graphql-dataloader-test-suite/tests/02_dataloader_with_server_cache.bal
Temporarily disable test case: testDataLoaderWithDifferentAliasForSameField
Related issue: https://github.com/ballerina-platform/ballerina-library/issues/7453
> Disable test testDataLoaderWithDifferentAliasForSameField

- .github/workflows/build-timestamped-master.yml
- .github/workflows/pull-request.yml
- gradle.properties
> Enable the tests in the GraphQL build 

- ballerina-tests/Ballerina.toml
- ballerina-tests/Dependencies.toml
- ballerina-tests/tests/25_input_objects.bal
- ballerina-tests/tests/resources/documents/input_object_with_unexpected_variable_fields1.graphql
- ballerina-tests/tests/resources/documents/input_object_with_unexpected_variable_fields2.graphql
- ballerina-tests/tests/resources/expected_results/input_object_with_unexpected_variable_fields1.json
- ballerina-tests/tests/resources/expected_results/input_object_with_unexpected_variable_fields2.json
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/field_validator_visitor.bal
- changelog.md
Fixes: [#7317](https://github.com/ballerina-platform/ballerina-library/issues/7317)
> [2201.10.X] Fix Service Crashing when Input Object Type Variable Value Includes an Additional Field
