graphql-ballerina/build.gradle
=> Fix BIR and JAR not publishing issue

README.md
=> Add status badges to the README.md file

graphql-ballerina/Ballerina.toml, graphql-ballerina/build.gradle, graphql-ballerina/modules/parser/tests/utils.bal, graphql-ballerina/modules/parser/utils.bal, graphql-ballerina/tests/document_validation.bal, graphql-ballerina/tests/utils.bal
=> Remove log apis

build.gradle, gradle.properties, graphql-ballerina/Ballerina.toml, graphql-ballerina/build.gradle, graphql-ballerina/engine.bal, graphql-ballerina/tests/03_listener_test.bal, graphql-ballerina/tests/07_errors_test.bal, graphql-ballerina/tests/values.bal
=> Add a Few Negative Tests

graphql-ballerina/listener.bal, graphql-ballerina/tests/03_listener_test.bal, graphql-ballerina/tests/04_resource_functions_with_input_parameters.bal, graphql-ballerina/tests/05_resource_functions_returning_records.bal, graphql-ballerina/tests/06_client_test.bal, graphql-ballerina/tests/07_errors_test.bal
=> Make port and httpListener a union

graphql-ballerina/common_utils.bal, graphql-ballerina/tests/07_errors_test.bal, graphql-ballerina/validator_visitor.bal
This PR will enable the validator to continue on errors, and send back all the errors to the client.
Fixes: [#736](https://github.com/ballerina-platform/ballerina-standard-library/issues/736)
=> Improve Argument Validation to Continue on Errors

build.gradle
=> Add missing lang repository

graphql-ballerina/Ballerina.toml, graphql-ballerina/common_utils.bal, graphql-ballerina/engine_utils.bal, graphql-ballerina/executor_visitor.bal, graphql-ballerina/modules/parser/field_node.bal, graphql-ballerina/modules/parser/types.bal, graphql-ballerina/records.bal, graphql-ballerina/tests/01_schema_generation.bal, graphql-ballerina/tests/07_errors_test.bal, graphql-ballerina/tests/08_resource_functions_returning_services.bal, graphql-ballerina/tests/expected_values.bal, graphql-ballerina/validator_visitor.bal, graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/Engine.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/Utils.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/utils/CallableUnitCallback.java
Now the Ballerina GraphQL services support the resource functions returning service objects. 
Although this supports execution, the validation can not be supported, since we do not have the information about the type of the returning service object. [#680](https://github.com/ballerina-platform/ballerina-spec/issues/680)
Fixes: [#643](https://github.com/ballerina-platform/ballerina-standard-library/issues/643)
Services similar to the following is now can be queried using a GraphQL query
```ballerina
service /graphql on new graphql:Listener(9097) {
isolated resource function get greet() returns service object {} {
return service object {
isolated resource function get generalGreeting() returns string {
return "Hello, world";
}
};
}
}
```
When this is queried using …
=> Add Support for Resources Returning Services

graphql-ballerina/Ballerina.toml, graphql-ballerina/common_utils.bal, graphql-ballerina/constants.bal, graphql-ballerina/modules/parser/constants.bal, graphql-ballerina/records.bal, graphql-ballerina/tests/07_errors_test.bal, graphql-ballerina/tests/10_resourcecs_returning_arrays.bal, graphql-ballerina/tests/expected_values.bal, graphql-ballerina/validator_visitor.bal, graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/Engine.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/Utils.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/schema/SchemaType.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/schema/TypeKind.java
With this PR, the Ballerina GraphQL module supports resources returning array values.
This also moves a step forward to map the Ballerina types with the GraphQL type names.
Fixes: [#646](https://github.com/ballerina-platform/ballerina-standard-library/issues/646)
Consider the following Ballerina service:
```ballerina
service /graphql on new graphql:Listener(9100) {
resource function get people() returns Person[] {
return people;
}
isolated resource function get ids() returns int[] {
return [0, 1, 2];
}
}
public type Address record {
string number;
string street;
string city;
};
public type Person record {
string name;
int age;
Address address;
};
Person p1 = {
name: "Sherlock Holmes",
age: 40,
address: {
number: "221/B",
street: "Baker Street",
city: "London"
} …
```
=> Add Support for Resources Returning Arrays

graphql-ballerina/Package.md, graphql-ballerina/errors.bal
> $subject + Add missing doc comments
=> Change module introduction to follow the convention

build.gradle, gradle.properties
=> Resolve transitive dependencies

graphql-ballerina/client.bal, graphql-ballerina/common_utils.bal, graphql-ballerina/engine_utils.bal, graphql-ballerina/listener_utils.bal, graphql-ballerina/modules/parser/lexer.bal, graphql-ballerina/modules/parser/tests/utils.bal, graphql-ballerina/modules/parser/utils.bal, graphql-ballerina/tests/utils.bal, graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/Engine.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/EngineUtils.java
* Error construction syntax change
* ResourceFunctionType -> ResourceMethodType
=> Update to lang syntax changes

.github/workflows/build-master.yml, .github/workflows/pull-request.yml
=> Archive error log on failure

graphql-ballerina/listener.bal, graphql-ballerina/listener_utils.bal, graphql-ballerina/modules/parser/lexer.bal, graphql-ballerina/records.bal, graphql-ballerina/types.bal, graphql-ballerina/validator_visitor.bal, graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/EngineUtils.java
* $Subject
* Removed unnecessary TODO comments
=> Improve Errors Returning from the Listener Functions

build.gradle, gradle.properties, graphql-ballerina/tests/02_document_validation.bal
$Subject
* removed ballerina-runtime module from the dependencies.
=> Add function pointers to test configs

build.gradle, gradle.properties
Replacing the stringutils module with regex module
=> Replace Stringutils Module with Regex

build-config/checkstyle/build.gradle, build.gradle, gradle.properties, settings.gradle
=> Remove version numbers from the build.gradle files

graphql-ballerina/client.bal, graphql-ballerina/errors.bal, graphql-ballerina/listener.bal, graphql-ballerina/tests/06_client_test.bal, graphql-ballerina/tests/07_errors_test.bal, graphql-ballerina/tests/08_resource_functions_returning_services.bal, graphql-ballerina/tests/09_resources_returning_union_types.bal, graphql-ballerina/tests/10_resources_returning_arrays.bal, graphql-ballerina/tests/11_introspection_queries.bal
=> Return error from client and listener init functions

graphql-ballerina/tests/02_document_validation.bal, graphql-ballerina/tests/03_listener_test.bal, graphql-ballerina/tests/04_resource_functions_with_input_parameters.bal, graphql-ballerina/tests/05_resource_functions_returning_records.bal
=> Update tests to handle error in http listener and client initialization

graphql-ballerina/build.gradle
$subject.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Update ballerina command to bal command

graphql-ballerina/Package.md
=> Update package.md file

graphql-ballerina/engine_utils.bal, graphql-ballerina/init.bal, graphql-ballerina/modules/parser/utils.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Change the name of the `java` langlib module to `jballerina.java`

graphql-ballerina/Ballerina.toml, graphql-ballerina/Dependencies.toml, graphql-ballerina/build.gradle
Fixes ballerina-platform/ballerina-lang#27988
=> Add Dependencies.toml

graphql-ballerina/build.gradle
=> Revert dependency toml file after build

build.gradle, gradle.properties, graphql-native/build.gradle
- Rename `checkStyle` plugin version variable
- Remove Jacoco configurations
=> Update build scripts

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, graphql-ballerina/build.gradle, graphql-ballerina/common_utils.bal, graphql-ballerina/tests/07_errors_test.bal, graphql-ballerina/validator_visitor.bal
- Currently, when an invalid argument is provided, the GraphQL engine crashes. This PR will fix it and send a proper response back.
- This also enables the test coverage JSON and archives it.
=> Fix Crashing when Invalid Argument is Provided

gradle.properties, graphql-ballerina/build.gradle
=> Update stdlib dependency versions

graphql-ballerina/build.gradle
=> Avoid runnig tests twice when publishing

graphql-ballerina/build.gradle
=> Refactor build dependencies

graphql-ballerina/build.gradle
=> Enable publishing testable jars

graphql-ballerina/Ballerina.toml
=> Remove module field from native dependency entry in toml file

README.md, graphql-ballerina/Package.md
=> Update Links and Descriptions in Package.md and Readme.md Files

.github/workflows/publish-release.yml, gradle.properties, graphql-ballerina/build.gradle
$Subject
Part of [#957](https://github.com/ballerina-platform/ballerina-standard-library/issues/957)
=> Enable publishing to ballerina central

build.gradle
=> Fix module version extracting

.github/workflows/build-master.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml
=> Update workflow scripts to increase readability

graphql-ballerina/errors.bal
=> Remove client related errors

build.gradle, graphql-ballerina/build.gradle
=> Re-order Build Tasks to Publish to the Ballerina Central

graphql-ballerina/build.gradle
=> Avoid Publishing to Central when Publishing to Maven Local

graphql-ballerina/build.gradle
=> Throw exception when central token not present

graphql-ballerina/build.gradle
=> Avoid publishing to central fro SNAPSHOT versions

graphql-ballerina/build.gradle
=> Fix the error when publishing to ballerina central

graphql-ballerina/engine.bal, graphql-ballerina/engine_utils.bal, graphql-ballerina/errors.bal, graphql-ballerina/tests/01_schema_generation.bal, graphql-ballerina/tests/07_resource_functions_returning_services.bal, graphql-ballerina/tests/08_resources_returning_union_types.bal, graphql-ballerina/validator_visitor.bal, graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/Engine.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/engine/EngineUtils.java
- Enabled validation for Typed services returned from a resource  function.
- Return an error when a resource is returning a service without a type.
Fixes: [#763](https://github.com/ballerina-platform/ballerina-standard-library/issues/763)
=> Improve Functionality of Resources Returning Service Objects

graphql-ballerina/build.gradle
=> Remove publishing testable jar and exec artifacts

build.gradle, gradle.properties, graphql-ballerina/Dependencies.toml, graphql-ballerina/build.gradle, graphql-ballerina/tests/03_listener_test.bal, graphql-ballerina/tests/11_listener_configurations_test.bal
$Subject
- Fixed a test failure due to HTTP API change
=> Rename Encoding Package Name to URL

README.md
=> Add Codecov Badge in Readme

graphql-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
=> Add extracted bala in the zip artifact

graphql-ballerina/engine.bal, graphql-ballerina/engine_utils.bal, graphql-ballerina/errors.bal, graphql-ballerina/listener.bal, graphql-ballerina/modules/parser/errors.bal, graphql-ballerina/modules/parser/tests/lexer_tests.bal, graphql-ballerina/modules/parser/tests/utils.bal, graphql-ballerina/records.bal, graphql-ballerina/tests/07_resource_functions_returning_services.bal, graphql-ballerina/tests/08_resources_returning_union_types.bal, graphql-ballerina/tests/11_listener_configurations_test.bal, graphql-ballerina/tests/utils.bal, graphql-native/src/main/java/io/ballerina/stdlib/graphql/schema/tree/SchemaGenerator.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/schema/tree/SchemaTreeGenerator.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/schema/tree/TypeTreeGenerator.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/utils/Utils.java
* Removed records types that extend the HTTP record types, that are now removed from the HTTP package. (Fixes: [#1069](https://github.com/ballerina-platform/ballerina-standard-library/issues/1069))
* Implement error inheritance (Fixes: [#990](https://github.com/ballerina-platform/ballerina-standard-library/issues/990))
* Mark file-related and io-related functions as isolated.
=> Implement Error Inheritance and Update HTTP Listener Related Records

graphql-ballerina/build.gradle
> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032
=> Add -c flag to build command

graphql-ballerina/Package.md
$Subject
Fixes: [#948](https://github.com/ballerina-platform/ballerina-standard-library/issues/948)
=> Update package.md file with the new features

gradle.properties
=> Upgrade task version

graphql-ballerina/tests/03_listener_test.bal, graphql-ballerina/tests/04_resource_functions_with_input_parameters.bal, graphql-ballerina/tests/05_resource_functions_returning_records.bal, graphql-ballerina/tests/06_errors_test.bal, graphql-ballerina/tests/07_resource_functions_returning_services.bal, graphql-ballerina/tests/08_resources_returning_union_types.bal, graphql-ballerina/tests/09_resources_returning_arrays.bal, graphql-ballerina/tests/10_introspection_queries.bal, graphql-ballerina/tests/11_listener_configurations_test.bal, graphql-ballerina/tests/12_hierarchical_resource_paths.bal, graphql-ballerina/tests/utils.bal
$Subject
Fixes: [#1092](https://github.com/ballerina-platform/ballerina-standard-library/issues/1092)
=> Fix test failure due to HTTP api change

graphql-ballerina/tests/utils.bal
=> Remove creating request object when sending a request

changelog.md
=> Add changelog.md

gradle.properties, graphql-ballerina/Ballerina.toml, graphql-ballerina/engine_utils.bal, graphql-ballerina/init.bal, graphql-ballerina/modules/parser/utils.bal, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/EngineUtils.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/IntrospectionUtils.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/parser/ParserUtils.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/InputValue.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/Schema.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/SchemaField.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/SchemaType.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/TypeKind.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/tree/Node.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/tree/SchemaGenerator.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/tree/SchemaTreeGenerator.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/tree/TypeTreeGenerator.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/utils/CallableUnitCallback.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/utils/ModuleUtils.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/utils/Utils.java
=> Change Native Package Name to Runtime

gradle.properties
=> Reorganize dependent modules

graphql-ballerina/common_utils.bal
Fixes: [#1179](https://github.com/ballerina-platform/ballerina-standard-library/issues/1179)
=> Replace string concatanation with string literal

graphql-ballerina/http_service.bal, graphql-ballerina/listener_utils.bal, graphql-ballerina/modules/parser/field_node.bal
Fixes failures due to [ballerina-lang#29119](https://github.com/ballerina-platform/ballerina-lang/pull/29119)
=> Fix unused variable with inferred type error

.github/pull_request_template.md, changelog.md
=> Update changelog for 2.0.0-alpha6

build.gradle, graphql-ballerina/build.gradle
=> Strip stdlib dependency version

graphql-ballerina/build.gradle
=> Fix Build Failure Due to Build Script Issue

graphql-compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/CompilerPluginTest.java, graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_9/Ballerina.toml, graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_9/service.bal, graphql-compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/GraphqlFunctionValidator.java, graphql-compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/PluginConstants.java
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1294
$title
=> Add validation for resource functions with return type error

changelog.md
=> Update changelog after 0.2.0-alpha8 release

.github/workflows/publish-release.yml, gradle.properties
=> Improve Release Workflow and Update Version to Beta

changelog.md, graphql-ballerina/engine_utils.bal, graphql-ballerina/executor_visitor.bal, graphql-ballerina/tests/02_document_validation.bal, graphql-ballerina/tests/09_resources_returning_arrays.bal, graphql-ballerina/tests/10_introspection_queries.bal, graphql-ballerina/tests/utils.bal, graphql-ballerina/validator_visitor.bal, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/CallableUnitCallback.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/FieldFinder.java
This PR will improve the Schema Introspection of a Ballerina GraphQL service.
Fixes: [#1329](https://github.com/ballerina-platform/ballerina-standard-library/issues/1329)
N/A
=> Improve Schema Introspection

changelog.md, graphql-ballerina/tests/17_advanced_service_types.bal
The issue is already fixed in the master. This PR will add a test for the scenario mentioned in the issue.
Fixes: [#1268](https://github.com/ballerina-platform/ballerina-standard-library/issues/1268)
N/A
=> Add Test for Requesting Invalid Field From Service Type Resource

changelog.md, graphql-ballerina/modules/parser/argument_node.bal, graphql-ballerina/modules/parser/document_node.bal, graphql-ballerina/modules/parser/field_node.bal, graphql-ballerina/modules/parser/fragment_node.bal, graphql-ballerina/modules/parser/nodes.bal, graphql-ballerina/modules/parser/operation_node.bal, graphql-ballerina/tests/19_auth_listener_configs.bal, graphql-ballerina/tests/20_distinct_service_unions.bal, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/FieldFinder.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/TypeFinder.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/Utils.java
Fixes: [#1368](https://github.com/ballerina-platform/ballerina-standard-library/issues/1368)
N/A
=> Fix Throwing NPE When Union Types Does not have a Name

changelog.md, graphql-compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/CompilerPluginTest.java, graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_5/service.bal, graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_5/service.bal, graphql-compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/GraphqlFunctionValidator.java
$title 
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1350
=> Allow the union of enum? as resource function input parameter

graphql-compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/CompilerPluginTest.java, graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_8/service.bal, graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_9/Ballerina.toml, graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_9/service.bal, graphql-compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/GraphqlFunctionValidator.java
=> Fix compiler plugin failure due to StackOverflow error

graphql-ballerina/auth_types.bal
=> Add missing documentations for auth-types

gradle.properties, graphql-ballerina/Dependencies.toml, graphql-ballerina/build.gradle
=> Add Security Modules to the Dependencies Toml

changelog.md, graphql-ballerina/annotation_processor.bal, graphql-ballerina/engine.bal, graphql-ballerina/http_service.bal, graphql-ballerina/listener.bal, graphql-ballerina/tests/11_listener_configurations_test.bal
$Subject
Fixes: [#1382](https://github.com/ballerina-platform/ballerina-standard-library/issues/1382)
N/A
=> Decouple the Engine and the Listener

graphql-ballerina/build.gradle
Update flag for coverage format from '--jacoco-xml' to '--coverage-format=xml'
=> Update flag for coverage format

graphql-examples/build.gradle, graphql-examples/resources/Dependencies.toml, graphql-examples/snowtooth/Dependencies.toml
=> Remove Dependencies.toml File Contents From Example Project

graphql-examples/snowtooth/query_service.bal
Fixes: Fix the bug in allLifts and allTrails query
=> Fix the bug in allLifts and allTrails query

build.gradle, changelog.md, graphql-ballerina/Module.md, graphql-ballerina/annotation_processor.bal, graphql-ballerina/annotations.bal, graphql-ballerina/engine.bal, graphql-ballerina/listener.bal, graphql-ballerina/tests/11_listener_configurations_test.bal, graphql-ballerina/tests/19_auth_listener_configs.bal, graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_6/service.bal, graphql-compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_3/service.bal
$Subject
Fixes: [#1398](https://github.com/ballerina-platform/ballerina-standard-library/issues/1398)
N/A
=> Change the ServiceConfiguration Record Name to ServiceConfig

graphql-examples/snowtooth/README.md, graphql-examples/snowtooth/query.bal
=> Update snowtooth example

changelog.md
=> Update the change log description

changelog.md, graphql-ballerina/tests/12_hierarchical_resource_paths.bal, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/CallableUnitCallback.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/EngineUtils.java
$Subject
Fixes: [#1378](https://github.com/ballerina-platform/ballerina-standard-library/issues/1378)
N/A
=> Fix Hierarchical Paths Returning Incorrect Values for Leaf Fields with the Same Name

graphql-examples/snowtooth/lift.bal, graphql-examples/snowtooth/trail.bal
=> Make Lift and Trail services isolated

changelog.md, graphql-ballerina/common_utils.bal, graphql-ballerina/modules/parser/parser.bal, graphql-ballerina/tests/14_fragments.bal, graphql-ballerina/tests/values.bal
$Subject
Fixes: [#1410](https://github.com/ballerina-platform/ballerina-standard-library/issues/1410)
N/A
=> Fix Inline Fragments Returning Non-requested Fields

changelog.md
=> Re-order the Changelog Entries

gradle.properties, graphql-ballerina/tests/11_listener_configurations_test.bal, graphql-ballerina/tests/auth_test_utils.bal
This reverts commit 37579beb4d893c6e944dad691f9fdcd0ee4df4da.
N/A
=> Revert "Fix Test Failures Due to HTTP Changes"

graphql-ballerina/Module.md, graphql-ballerina/Package.md
$Subject
Fixes: [#1418](https://github.com/ballerina-platform/ballerina-standard-library/issues/1418)
N/A
=> Fix Invalid Link and Description in Documentation

.github/workflows/publish-release.yml, gradle.properties
=> Update ballerina plugin version to 0.9.0

graphql-examples/snowtooth/lift.bal, graphql-examples/snowtooth/modules/datasource/datasource.bal, graphql-examples/snowtooth/query.bal, graphql-examples/snowtooth/trail.bal
=> Make snowtooth isolated

changelog.md, graphql-ballerina/tests/12_hierarchical_resource_paths.bal, graphql-ballerina/tests/14_fragments.bal, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/CallableUnitCallback.java
$Subject
Fixes: [#1447](https://github.com/ballerina-platform/ballerina-standard-library/issues/1447)
N/A
=> Fix Fragments Resulting Empty Values when Service Object is Returned

graphql-examples/snowtooth/lift.bal, graphql-examples/snowtooth/trail.bal
=> Remove additional isolated key words

.github/workflows/pull-request.yml
=> Change to Setup Java Action Version 2 in Windows Build

graphql-ballerina/Package.md
=> Update Links in Package.md to Open in New Tabs

changelog.md, graphql-ballerina/engine_utils.bal, graphql-ballerina/executor_visitor.bal, graphql-ballerina/tests/09_resources_returning_arrays.bal, graphql-ballerina/tests/resources/expected_results/complex_array.json, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/CallbackHandler.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ResourceCallback.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ResponseGenerator.java
$Subject
Fixes: [#1190](https://github.com/ballerina-platform/ballerina-standard-library/issues/1190)
N/A
=> Make GraphQL Service Non-Blocking

changelog.md, graphql-ballerina/engine_utils.bal, graphql-ballerina/executor_visitor.bal, graphql-ballerina/tests/09_resources_returning_arrays.bal, graphql-ballerina/tests/resources/expected_results/complex_array.json, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/CallbackHandler.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ResourceCallback.java, graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ResponseGenerator.java
$Subject
Fixes: [#1190](https://github.com/ballerina-platform/ballerina-standard-library/issues/1190)
=> Make GraphQL Service Invocation a Non-Blocking Call

graphql-examples/snowtooth/README.md
=> Update the README.md

graphql-examples/snowtooth/query.bal
=> Refactor the code

graphql-examples/build.gradle
=> Improve Build Script to Skip Example Tests When Needed

graphql-compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/GraphqlFunctionValidator.java, graphql-compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/PluginConstants.java
=> Update Invalid Accessor Compilation Error Diagnostics

changelog.md, graphql-ballerina/modules/parser/records.bal, graphql-ballerina/records.bal, graphql-ballerina/response_coerce_visitor.bal, graphql-examples/build.gradle
$Subject
Fixes: [#1566](https://github.com/ballerina-platform/ballerina-standard-library/issues/1566)
N/A
=> Make Locations Field Optional in GraphQL Errors

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/pull-request.yml, ballerina/modules/parser/field_node.bal, ballerina/modules/parser/parser.bal, ballerina/modules/parser/tests/parser_tests.bal, ballerina/response_coerce_visitor.bal, ballerina/tests/21_aliases.bal, ballerina/tests/resources/documents/alias.txt, ballerina/tests/resources/documents/alias_on_hierarchical_resources.txt, ballerina/tests/resources/documents/alias_on_service_objects_union.txt, ballerina/tests/resources/documents/alias_with_invalid_field_name.txt, ballerina/tests/resources/documents/same_field_with_multiple_alias.txt, ballerina/tests/resources/documents/same_field_with_multiple_alias_different_subfields.txt, ballerina/tests/resources/expected_results/alias_on_hierarchical_resources.json, ballerina/tests/resources/expected_results/alias_on_service_objects_union.json, ballerina/tests/resources/expected_results/same_field_with_multiple_alias.json, ballerina/tests/resources/expected_results/same_field_with_multiple_alias_different_subfields.json, changelog.md, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/EngineUtils.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ResponseGenerator.java
$Subject
Fixes: [#1634](https://github.com/ballerina-platform/ballerina-standard-library/issues/1634)
N/A
=> Add Alias Support for GraphQL Queries

ballerina/modules/parser/constants.bal, ballerina/modules/parser/document_node.bal, ballerina/modules/parser/tests/lexer_tests.bal, ballerina/modules/parser/tests/parser_tests.bal, ballerina/records.bal, ballerina/response_coerce_visitor.bal, ballerina/tests/03_document_validation.bal, ballerina/tests/11_configurations_test.bal, ballerina/tests/15_enums.bal, ballerina/tests/19_distinct_service_unions.bal, ballerina/tests/resources/documents/nested_fragments.txt, ballerina/types.bal, native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/SchemaRecordGenerator.java
=> Remove Unnecessary Empty Lines and TODO Comments

.gitignore, ballerina/common_utils.bal, ballerina/constants.bal, ballerina/engine_utils.bal, ballerina/executor_visitor.bal, ballerina/tests/03_document_validation.bal, ballerina/tests/10_introspection_queries.bal, ballerina/tests/resources/documents/type_introspection.txt, ballerina/tests/resources/documents/type_introspection_in_invalid_place.txt, ballerina/tests/resources/documents/type_introspection_without_type_name_argument.txt, ballerina/tests/resources/documents/type_name_introspection_in_fragments.txt, ballerina/tests/resources/documents/type_name_introspection_on_service_types.txt, ballerina/tests/resources/documents/type_name_introspection_on_union_of__service_types.txt, ballerina/tests/resources/expected_results/mutation_type_introspection.json, ballerina/tests/resources/expected_results/type_introspection.json, ballerina/tests/resources/expected_results/type_introspection_in_invalid_place.json, ballerina/tests/resources/expected_results/type_introspection_without_type_name_argument.json, ballerina/tests/resources/expected_results/type_name_introspection_in_fragments.json, ballerina/tests/resources/expected_results/type_name_introspection_on_service_types.json, ballerina/tests/resources/expected_results/type_name_introspection_on_union_of__service_types.json, ballerina/tests/resources/expected_results/type_name_introspection_on_union_of_record_types.json, ballerina/validator_visitor.bal, changelog.md, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/EngineUtils.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ExecutionContext.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ResourceCallback.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ResponseGenerator.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ResultContext.java
Fixes: [#1723](https://github.com/ballerina-platform/ballerina-standard-library/issues/1723)
Fixes: [#1728](https://github.com/ballerina-platform/ballerina-standard-library/issues/1728)
Fixes: [#1730](https://github.com/ballerina-platform/ballerina-standard-library/issues/1730)
The following introspection queries will be now supported:
- Type Name Introspection
```
{
profile {
__typename
}
}
```
- Type Introspection
```
{
__type(name: "Person") {
name
kind
fields {
name
}
}
}
```
=> Fix and Improve Introspection Support

ballerina/Module.md
$Subject
Related: [#1492](https://github.com/ballerina-platform/ballerina-standard-library/issues/1492)
=> Update API Docs to add Documentation on Mutations

gradle.properties
$Subject
Related: [#1334](https://github.com/ballerina-platform/ballerina-standard-library/issues/1334)
N/A
=> Update to 1.0.0 Version

ballerina/tests/10_introspection_queries.bal, ballerina/tests/resources/documents/introspection_on_inputs_with_default_values.txt, ballerina/tests/resources/expected_results/introspection_on_inputs_with_default_values.json, ballerina/tests/test_services.bal, changelog.md, native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/FieldFinder.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/types/InputValue.java
When an input value has a default value, no matter if it is a nullable type or not, the Ballerina schema always shows it as a nullable type. This PR will fix this. 
Fixes: [#1818](https://github.com/ballerina-platform/ballerina-standard-library/issues/1818)
N/A
=> Fix NON_NULL Inputs with Default Values Showed as Nullable Values

.gitignore, ballerina/Dependencies.toml, ballerina/modules/parser/constants.bal, ballerina/modules/parser/field_node.bal, ballerina/modules/parser/fragment_node.bal, ballerina/modules/parser/nodes.bal, ballerina/modules/parser/operation_node.bal, ballerina/modules/parser/parent_node.bal, ballerina/modules/parser/parser.bal, ballerina/tests/26_nullable_values.bal, ballerina/tests/records.bal, ballerina/tests/test_services.bal, ballerina/validator_visitor.bal, changelog.md, native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/FieldFinder.java
Fixes: [#1879](https://github.com/ballerina-platform/ballerina-standard-library/issues/1879)
Fixes: [#1845](https://github.com/ballerina-platform/ballerina-standard-library/issues/1845)
=> Fix Null Values not Supported in Documents 

ballerina/Dependencies.toml, ballerina/common_utils.bal, ballerina/records.bal, ballerina/validator_visitor.bal, ballerina/variable_validator.bal
=> Make Type Name Field Required

.github/workflows/publish-release.yml, .github/workflows/trivy-scan.yml
This PR integrates the [Trivy](https://github.com/aquasecurity/trivy) vulnerability scanner for the repository file system and it will check and generate the report daily or on-demand and before the release.
Related Issue: [#1849](https://github.com/ballerina-platform/ballerina-standard-library/issues/1849)
N/A
=> Integrate Trivy Vulnerability Scanner

.github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/trivy-scan.yml, ballerina/Dependencies.toml, ballerina/common_utils.bal, ballerina/records.bal, ballerina/validator_visitor.bal, ballerina/variable_validator.bal
=> Remove Scan Ref from Trivy Scan

.github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/trivy-scan.yml
=> Add scan ref to trivy scan

ballerina/Dependencies.toml, ballerina/tests/22_variables.bal, ballerina/tests/25_input_objects.bal, ballerina/tests/resources/documents/input_object_with_missing_nullable_variable_value.txt, ballerina/tests/resources/expected_results/input_object_with_missing_nullable_variable_value.json, ballerina/tests/resources/expected_results/scalar_type_variable_with_input_object_value.json, ballerina/tests/resources/expected_results/variable_default_null_value_with_non_null_type.json, ballerina/tests/resources/expected_results/variable_with_invalid_default_value1.json, ballerina/tests/resources/expected_results/variable_with_invalid_default_value2.json, ballerina/variable_validator.bal, changelog.md
Fixes: [#1911](https://github.com/ballerina-platform/ballerina-standard-library/issues/1911)
Fixes: [#1912](https://github.com/ballerina-platform/ballerina-standard-library/issues/1912)
N/A
=> Fix Variable Default Value Validation Error

ballerina/auth_utils.bal, changelog.md
$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1920
=> Fix GraphQL auth error format

.github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/trivy-scan.yml
$Subject
Related Issue: [#1958](https://github.com/ballerina-platform/ballerina-standard-library/issues/1958)
N/A
=> Skip Build Directory from the Trivy Scan

ballerina/tests/22_variables.bal, ballerina/tests/resources/expected_results/invalid_enum_type_default_value_with_variables.json, ballerina/variable_validator.bal, changelog.md
Fixes: [#1984](https://github.com/ballerina-platform/ballerina-standard-library/issues/1984)
Fixes: [#1983](https://github.com/ballerina-platform/ballerina-standard-library/issues/1983)
N/A
=> Fix Variable Default Value Validation Errors

ballerina/modules/parser/parser.bal, ballerina/modules/parser/records.bal, ballerina/modules/parser/tests/parser_tests.bal, ballerina/tests/22_variables.bal, ballerina/tests/resources/expected_results/enum_type_default_value_with_string_literal.json, ballerina/tests/resources/expected_results/variable_with_invalid_default_value3.json, ballerina/variable_validator.bal, changelog.md
Fixes: [#1990](https://github.com/ballerina-platform/ballerina-standard-library/issues/1990)
N/A
=> Fix Allowing Invalid Values as Variable Default Value

docs/proposals/context.md
$Subject
Related: [#1906](https://github.com/ballerina-platform/ballerina-standard-library/issues/1906)
N/A
=> Add Context Proposal

ballerina/tests/27_context.bal, ballerina/tests/test_services.bal, changelog.md, native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/FieldFinder.java
$Subject
Fixes: [#1998](https://github.com/ballerina-platform/ballerina-standard-library/issues/1998)
=> Fix Ignoring Parameters After the Context Parameter

docs/proposals/context.md
=> Update the names to github handle

ballerina/Module.md
$Subject
Fixes: [#2009](https://github.com/ballerina-platform/ballerina-standard-library/issues/2009)
N/A
=> Add Documentation for Context Support

.github/workflows/publish-release.yml
=> Clean before release

.github/workflows/build-timestamped-master.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml
$Subejct
Related: [#2033](https://github.com/ballerina-platform/ballerina-standard-library/issues/2033)
N/A
=> Increase Trivy Scan Timeout and Migrate to CodeCov v2

ballerina/common_utils.bal, ballerina/constants.bal, ballerina/default_values.bal, ballerina/directive_visitor.bal, ballerina/engine.bal, ballerina/listener.bal, ballerina/listener_utils.bal, ballerina/tests/28_directives.bal, ballerina/tests/resources/documents/directives.txt, ballerina/tests/resources/documents/directives_in_invalid_locations1.txt, ballerina/tests/resources/documents/directives_with_duplicate_fields.txt, ballerina/tests/resources/documents/directives_with_unknown_arguments.txt, ballerina/tests/resources/documents/directives_with_variables_and_fragments.txt, ballerina/tests/resources/documents/directives_without_argument.txt, ballerina/tests/resources/documents/duplicate_directives_in_same_location.txt, ballerina/tests/resources/documents/multiple_directive_usage_in_fields.txt, ballerina/tests/resources/documents/unknown_directives.txt, ballerina/tests/resources/expected_results/directives_in_invalid_locations1.json, ballerina/tests/resources/expected_results/directives_with_unknown_arguments.json, ballerina/tests/resources/expected_results/directives_without_argument.json, ballerina/tests/resources/expected_results/duplicate_directives_in_same_location.json, ballerina/tests/resources/expected_results/graphql_playground_introspection_query.json, ballerina/tests/resources/expected_results/unknown_directives.json, ballerina/validator_visitor.bal, ballerina/variable_validator.bal, changelog.md, gradle.properties
=> Sync with master branch 

ballerina/Module.md
$Subject
Fixes: [#2375](https://github.com/ballerina-platform/ballerina-standard-library/issues/2375)
N/A
=> Update API Docs

examples/build.gradle
=> Remove --with-tests

native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java
> $subject
Related to: [#2383](https://github.com/ballerina-platform/ballerina-standard-library/issues/2383)
=> Migrate to latests ballerina runtime APIs

ballerina/types.bal, changelog.md, gradle.properties
> $subject
Related to: [#2398](https://github.com/ballerina-platform/ballerina-standard-library/issues/2398)
=> Make GraphQL service-type distinct

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, examples/build.gradle, examples/snowtooth/Dependencies.toml
=> Add Offline Flag to Examples Build

docs/proposals/context.md
=> Fix typos in proposals

ballerina/http_service.bal, changelog.md
$Subject
Fixes: [#2437](https://github.com/ballerina-platform/ballerina-standard-library/issues/2437)
N/A
=> Pass `http:RequestContext` to the `graphql:Context` Init Function

ballerina/tests/25_input_objects.bal, ballerina/tests/resources/expected_results/input_object_with_nested_input_object_variables.json, changelog.md, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java
Fixes: [#2480](https://github.com/ballerina-platform/ballerina-standard-library/issues/2480)
=> Fix Input Object type variables returning type cast error

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, examples/snowtooth/Dependencies.toml, gradle.properties
$subject
Part of [ballerina-platform/ballerina-standard-library#2478](https://github.com/ballerina-platform/ballerina-standard-library/issues/2478)
=> Update distribution to slbeta6 

ballerina/tests/29_list_type_inputs.bal, ballerina/tests/resources/documents/input_object_type_variables_inside_list_value.graphql, ballerina/tests/resources/documents/invalid_variables_inside_list_value.graphql, ballerina/tests/resources/expected_results/invalid_variables_inside_list_value.json, ballerina/variable_validator.bal, changelog.md
Fixes: [#2481](https://github.com/ballerina-platform/ballerina-standard-library/issues/2481)
=> Fix ignoring type validation of variables in a list

ballerina/auth_utils.bal, ballerina/tests/auth_test_utils.bal
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2486
=> Refactor security implementation

ballerina/common_utils.bal, ballerina/tests/25_input_objects.bal, ballerina/tests/29_list_type_inputs.bal, ballerina/tests/resources/documents/input_object_with_invalid_arguments2.graphql, ballerina/tests/resources/documents/input_object_with_missing_variables_arguments.graphql, ballerina/tests/resources/expected_results/enum_type_default_value_with_string_literal.json, ballerina/tests/resources/expected_results/input_object_with_invalid_arguments2.json, ballerina/tests/resources/expected_results/input_object_with_missing_arguments.json, ballerina/tests/resources/expected_results/input_object_with_missing_variables_arguments.json, ballerina/tests/resources/expected_results/input_variables_with_empty_input_object_value.json, ballerina/tests/resources/expected_results/input_variables_with_invalid_argument_type.json, ballerina/tests/resources/expected_results/invalid_list_type_within_input_objects.json, ballerina/tests/resources/expected_results/invalid_list_type_within_input_objects_with_variables.json, ballerina/tests/resources/expected_results/list_type_with_invalid_variable_default_values_1.json, ballerina/tests/resources/expected_results/list_type_with_invalid_variable_default_values_2.json, ballerina/tests/resources/expected_results/list_type_with_invalid_variable_default_values_3.json, ballerina/tests/resources/expected_results/list_type_with_invalid_variable_default_values_4.json, ballerina/tests/resources/expected_results/list_type_with_invalid_variable_default_values_5.json, ballerina/tests/resources/expected_results/list_type_with_invalid_variable_default_values_7.json, ballerina/tests/resources/expected_results/nullable_list_type_input_with_invalid_value.json, ballerina/tests/resources/expected_results/scalar_type_variable_with_input_object_value.json, ballerina/tests/resources/expected_results/variable_default_null_value_with_non_null_type.json, ballerina/tests/resources/expected_results/variable_with_invalid_default_value1.json, ballerina/tests/resources/expected_results/variable_with_invalid_default_value2.json, ballerina/tests/resources/expected_results/variable_with_invalid_default_value3.json, ballerina/validator_visitor.bal, ballerina/variable_validator.bal, changelog.md
Fixes: [#2076](https://github.com/ballerina-platform/ballerina-standard-library/issues/2076)
=> Refactor GraphQL error messages

ballerina/listener_utils.bal, ballerina/tests/30_file_upload.bal, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/EngineUtils.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/TypeFinder.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/utils/Utils.java
Fixes: [#2500](https://github.com/ballerina-platform/ballerina-standard-library/issues/2500)
=> Fix returning NPE when multiple file uploading

docs/proposals/file_upload.md
$subject
Related: [#1882](https://github.com/ballerina-platform/ballerina-standard-library/issues/1882)
N/A
=> Add file upload proposal

docs/proposals/compile-time-schema-generation.md
$Subject
Fixes: part of [#2047](https://github.com/ballerina-platform/ballerina-standard-library/issues/2047)
N/A
=> Add Compile Time Schema Generation Proposal

ballerina/Module.md, docs/proposals/context.md
=> Update Documentation with the Changes to `context.add` Method

load-tests/snowtooth/scripts/snowtooth-test-plan.jmx
=> Fix test duration and loop count

ballerina/auth_types.bal, ballerina/auth_utils.bal
=> Improve auth desugar implementation

load-tests/snowtooth/deployment/ingress.yaml
=> Update Load Test Service Name

load-tests/snowtooth/scripts/run.sh
=> Reduce Number of Concurrent Users in Load Tests

ballerina/annotations.bal
Fixes: [#2544](https://github.com/ballerina-platform/ballerina-standard-library/issues/2544)
N/A
=> Add missing documentation in GraphQL service config

ballerina/response_formatter.bal, ballerina/tests/19_distinct_service_unions.bal, ballerina/tests/object_types.bal, ballerina/tests/resources/expected_results/complex_introspection_query.json, ballerina/tests/resources/expected_results/complex_introspection_query_with_other_fields.json, changelog.md
Fixes: [#2552](https://github.com/ballerina-platform/ballerina-standard-library/issues/2552)
N/A
=> Fix returning error when querying GraphQL union types

ballerina/Dependencies.toml, ballerina/Module.md, ballerina/tests/19_distinct_service_unions.bal, ballerina/tests/object_types.bal, ballerina/tests/resources/documents/union_type_names.graphql, ballerina/tests/resources/expected_results/union_type_names.json, ballerina/tests/test_services.bal, changelog.md, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/TypeFinder.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/schema/Utils.java
$Subject
Fixes: [#2598](https://github.com/ballerina-platform/ballerina-standard-library/issues/2598)
N/A
=> Fix Union Type Names not Resolving Correctly when the Field is Nullable

ballerina/auth_utils.bal, ballerina/engine_utils.bal, ballerina/fragment_visitor.bal, ballerina/listener.bal, ballerina/listener_utils.bal, ballerina/modules/parser/char_reader.bal, ballerina/modules/parser/document_node.bal, ballerina/modules/parser/lexer.bal, ballerina/modules/parser/operation_node.bal, ballerina/modules/parser/parser.bal, ballerina/modules/parser/tests/char_reader_tests.bal, ballerina/modules/parser/tests/lexer_tests.bal, ballerina/modules/parser/tests/parser_tests.bal, ballerina/modules/parser/utils.bal, ballerina/query_depth_validator.bal, ballerina/records.bal, ballerina/tests/09_arrays.bal, ballerina/tests/test_services.bal, ballerina/validator_visitor.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_22/service.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_11/service.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_2/service.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_7/service.bal, examples/snowtooth/tests/utils.bal
$Subject
Fixes: [#2244](https://github.com/ballerina-platform/ballerina-standard-library/issues/2244)
=> Refactor Ballerina Code to Avoid Anti-patterns

ballerina/tests/utils.bal
Fixes: [#2244](https://github.com/ballerina-platform/ballerina-standard-library/issues/2244)
N/A
=> Make GraphQL Test Services Isolated

ballerina/common_utils.bal, ballerina/fragment_visitor.bal, ballerina/tests/14_fragments.bal, ballerina/tests/resources/documents/fragments_spread_itself.graphql, ballerina/tests/resources/documents/fragments_with_cycles.graphql, ballerina/tests/resources/documents/fragments_with_multiple_cycles.graphql, ballerina/tests/resources/documents/fragments_with_multiple_cycles_in_same_fragment.graphql, ballerina/tests/resources/expected_results/fragments_with_cycles.json, ballerina/tests/resources/expected_results/fragments_with_multiple_cycles.json, ballerina/tests/resources/expected_results/fragments_with_multiple_cycles_in_same_fragment.json, changelog.md
Fixes: [#2640](https://github.com/ballerina-platform/ballerina-standard-library/issues/2640)
N/A
=> Fix Inter-Dependent Fragments Returning Stack Overflow Error

docs/spec/spec.md
=> Update the introduction part of the spec

.github/workflows/process-load-test-result.yml, .github/workflows/trigger-load-tests.yml
=> Update Load Test Processing Workflow to wait for CodeCov

.github/workflows/process-load-test-result.yml
=> Check for failures in loadtest processing workflow

changelog.md, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/CompilerPluginTest.java, compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_28/service.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_17/Ballerina.toml, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_17/service.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/validator/FunctionValidator.java
$Subject
Fixes: [#2656](https://github.com/ballerina-platform/ballerina-standard-library/issues/2656)
Check the issue.
=> Fix Compiler Plugin Crash when Recursive Record Definitions Present

.github/workflows/process-load-test-result.yml, ballerina/Dependencies.toml
=> Fix load test workflow

ballerina/Ballerina.toml, build-config/resources/Ballerina.toml
=> Update Distribution Version

ballerina/Dependencies.toml, examples/starwars/human.bal, examples/starwars/service.bal, examples/starwars/starship.bal, examples/starwars/tests/tests.bal
Fixes: [#2747](https://github.com/ballerina-platform/ballerina-standard-library/issues/2747)
=> Refactor GraphQL `starwars` Example

ballerina/tests/25_input_objects.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/validator/ServiceAnalyzer.java, gradle.properties
$Subject
Fixes: [#2679](https://github.com/ballerina-platform/ballerina-standard-library/issues/2679)
N/A
=> Update the Lang Version to 2201.0.1

ballerina/Dependencies.toml, ballerina/listener_utils.bal, ballerina/modules/parser/lexer.bal, ballerina/modules/parser/tests/lexer_tests.bal, ballerina/modules/parser/tests/parser_tests.bal, ballerina/tests/11_configurations_test.bal
Fixes: [#2844](https://github.com/ballerina-platform/ballerina-standard-library/issues/2844)
N/A
=> Remove Unnecessary Usage of `var` Type

.github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/trivy-scan.yml
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2902
=> Update Trivy Scan-Type to Enable JAR Scanning

ballerina-tests/tests/37_interfaces.bal, ballerina-tests/tests/resources/documents/interfaces_with_invalid_field.graphql, ballerina-tests/tests/resources/documents/interfaces_with_nested_fragments.graphql, ballerina-tests/tests/resources/documents/interfaces_with_type_name_introspection.graphql, ballerina-tests/tests/resources/expected_results/interfaces_with_invalid_field.json, ballerina-tests/tests/resources/expected_results/interfaces_with_nested_fragments.json, ballerina-tests/tests/resources/expected_results/interfaces_with_type_name_introspection.json, ballerina/common_utils.bal, ballerina/validator_visitor.bal, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/EngineUtils.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ResponseGenerator.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/utils/Utils.java
$Subject
Fixes: [#2917](https://github.com/ballerina-platform/ballerina-standard-library/issues/2917)
N/A
=> Fix nested fragments on interfaces returning empty values

ballerina-tests/build.gradle
$Subject
The code coverage for the master branch is not updated due to this.
=> Fix Gradle publish Task Not Running the Ballerina Tests

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, gradle.properties
=> Update Dependency Versions

gradle.properties
=> Bump the lang version to 2201.1.0-rc1.12

changelog.md
=> Remove GraphQL interface support entry from changelog

gradle.properties
=> Bump the Lang Version to 2201.1.0-rc1.13

README.md, ballerina/Module.md, ballerina/Package.md
Fixes: [#2947](https://github.com/ballerina-platform/ballerina-standard-library/issues/2947)
=> Update the API docs to describe Subscription support

docs/proposals/subscriptions.md
=> Modify the subscriptions proposal

changelog.md, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/SchemaGenerationTest.java, compiler-plugin-tests/src/test/resources/ballerina_sources/generator_tests/22_graphql_service_with_http_service/Ballerina.toml, compiler-plugin-tests/src/test/resources/ballerina_sources/generator_tests/22_graphql_service_with_http_service/service.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GraphqlSourceModifier.java
$Subject
Fixes: [#2959](https://github.com/ballerina-platform/ballerina-standard-library/issues/2959)
N/A
=> Fix code modifier service removal

docs/spec/spec.md
=> Remove the Issue Section from the Spec

docs/spec/spec.md
=> Update the Introduction and Contents Header Level

ballerina-tests/tests/10_introspection_queries.bal, ballerina-tests/tests/resources/documents/type_introspection_with_alias.graphql, ballerina-tests/tests/resources/expected_results/type_introspection_with_alias.json, ballerina/executor_visitor.bal
$Subject
Fixes: [#3021](https://github.com/ballerina-platform/ballerina-standard-library/issues/3021)
N/A
=> Fix introspection not working with aliases

README.md
=> Fix Trivy badge in README.md

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Bump stdlib module versions

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml
=> Update Central Publish Workflow to Publish to Dev and Stage Envs

ballerina-tests/tests/interceptors.bal, ballerina/types.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/validator_tests/invalid_service_37/service.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/validator_tests/invalid_service_4/service.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/validator_tests/valid_service_23/service.bal, docs/proposals/interceptors.md, docs/spec/spec.md
=> Update Spec with GraphQL Interceptors

.github/workflows/central-publish.yml
=> Update the central publich workflow to publish to stage and dev central

.github/workflows/update-spec.yml
$subject
Related to [#3154](https://github.com/ballerina-platform/ballerina-standard-library/issues/3154)
=> Add Stdlib Specs Update Workflow

ballerina-tests/tests/auth_test_utils.bal
=> Fix Compiler Hint on Making AuthResponse Public

changelog.md, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/ServiceValidationTest.java, compiler-plugin-tests/src/test/resources/ballerina_sources/validator_tests/invalid_service_38/service.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/service/errors/CompilationError.java, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/service/errors/ErrorCode.java, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/service/errors/ErrorMessage.java, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/service/validator/ServiceValidator.java
$Subject
Fixes: [#3173](https://github.com/ballerina-platform/ballerina-standard-library/issues/3173)
=> Update Anonymous Record Error Message

ballerina-tests/Dependencies.toml, ballerina/constants.bal, ballerina/listener_utils.bal, ballerina/websocket_utils.bal
=> Modify the GraphiQL endpoint url by `Host` request header

docs/spec/spec.md
$Subject
Fixes: [#3065](https://github.com/ballerina-platform/ballerina-standard-library/issues/3065)
N/A
=> Make the Record Types Used in GraphQL Examples Closed and Update the Spec

gradle.properties
Fixes:  [#3172](https://github.com/ballerina-platform/ballerina-standard-library/issues/3172)
=> Update the Websocket version to fix the intermittent error

ballerina/engine.bal, ballerina/response_generator.bal, changelog.md, docs/spec/spec.md
$Subject
Fixes: [#3260](https://github.com/ballerina-platform/ballerina-standard-library/issues/3260)
Consider the following code:
```ballerina
service on new graphql:Listener(4000) {
resource function get greeting(string name) returns string|error {
if name == "error" {
return error("Invalid name");
}
return "Hello, " + name;
}
}
```
When the following document is sent to this service:
```graphql
{
greeting(name: "error")
}
```
The following will be logged to the stderr:
```shell
time = 2022-08-17T17:37:56.764+05:30 level = ERROR module = ballerina/graphql message = "Invalid name" stackTrace = ["callableName: $get$greeting moduleName: thisarug.hello.0.$anonType$_1 fileName: main.bal lineNumber: 6"]
```
=> Log the Errors Occurred in GraphQL Resolvers

ballerina-tests/tests/resources/expected_results/introspection_on_inputs_with_default_values.json, changelog.md, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/SchemaGenerator.java
$Subject
Fixes: [#2897](https://github.com/ballerina-platform/ballerina-standard-library/issues/2897)
=> Fix Schema not Generating for Default Values

ballerina/auth_utils.bal, ballerina/listener_utils.bal, gradle.properties
=> Fix Compilation Errors Due to Type Narrowing Change

ballerina-tests/tests/test_services.bal, ballerina/listener.bal, ballerina/types.bal, changelog.md, docs/proposals/graphiql-client.md, docs/spec/spec.md
> Subject
Fixes: [#3288](https://github.com/ballerina-platform/ballerina-standard-library/issues/3288)
N/A
=> Rename the GraphiQL Config 'enable' to 'enabled'

ballerina-tests/tests/29_list_type_inputs.bal, ballerina-tests/tests/resources/expected_results/introspection_on_inputs_with_default_values.json, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/SchemaGenerator.java
Fixes: [#3307](https://github.com/ballerina-platform/ballerina-standard-library/issues/3307)
=> Fix type wrapped with NON-NULL for input with default values

ballerina-tests/tests/29_list_type_inputs.bal, ballerina-tests/tests/resources/expected_results/introspection_on_inputs_with_default_values.json, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/SchemaGenerator.java
This reverts commit 8d837fc070e9e7e09c4423ccf9cd563897d0797b.
Fixes: [#3307](https://github.com/ballerina-platform/ballerina-standard-library/issues/3307)
=> Revert "Fix type wrapped with NON-NULL for input with default values"

changelog.md
=> Update changelog.md for path release v1.4.1

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, gradle.properties, native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/graphql-native/resource-config.json, native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/graphql-native/serialization-config.json
Fixes: [3438](https://github.com/ballerina-platform/ballerina-standard-library/issues/3438)
=> Add native image build configurations

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/engine.bal, ballerina/engine_utils.bal, changelog.md, docs/spec/spec.md, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/EngineUtils.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ResourceCallback.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ResponseGenerator.java
$Subject
Fixes: [#3457](https://github.com/ballerina-platform/ballerina-standard-library/issues/3457)
=> Log the Errors Returned From the Resolvers

docs/spec/spec.md
=> Fix a Typo in the Spec

compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/SchemaGenerationTest.java, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/ServiceValidationTest.java, compiler-plugin-tests/src/test/resources/ballerina_sources/generator_tests/27_sdl_file_generation_warnings/Ballerina.toml, compiler-plugin-tests/src/test/resources/ballerina_sources/generator_tests/27_sdl_file_generation_warnings/service.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/validator_tests/17_record_types/service.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/validator_tests/22_interceptors/service.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GraphqlSourceModifier.java, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/SdlFileGenerator.java
Fixes: [#3465](https://github.com/ballerina-platform/ballerina-standard-library/issues/3465)
N/A
=> Improve the GraphQL Compiler Plugin Tests

changelog.md, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/SchemaGenerationTest.java, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/ServiceAnalysisTask.java, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GraphqlModifierContext.java, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GraphqlSourceModifier.java
=> Disable SDL File Generation

ballerina/Dependencies.toml, gradle.properties
=> Update the Cache Version to 3.3.0

commons/build.gradle, commons/src/main/java/io/ballerina/stdlib/graphql/commons/Utils.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/DefaultDirective.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/Description.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/Directive.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/DirectiveLocation.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/EnumValue.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/Field.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/FieldName.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/InputValue.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/IntrospectionField.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/IntrospectionType.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/ScalarType.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/Schema.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/Type.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/TypeKind.java, commons/src/main/java/io/ballerina/stdlib/graphql/commons/types/TypeName.java, commons/src/main/java/module-info.java
Recent license header changes should apply to the newly created files. But some of the files from #979 have incorrect license header values. This PR will fix them.
N/A
=> Update Incorrect License Headers

ballerina-tests/Dependencies.toml, ballerina/websocket_service.bal, changelog.md
Fixes: [#3545](https://github.com/ballerina-platform/ballerina-standard-library/issues/3545)
=> Fix Subscription Operations Allowed Before Server Has Acknowledged the Connection

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina-tests/tests/13_tables.bal, ballerina-tests/tests/records.bal, ballerina-tests/tests/test_services.bal, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, changelog.md, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/SchemaGenerator.java
Fixes: [#3556](https://github.com/ballerina-platform/ballerina-standard-library/issues/3556)
=> Fix returning runtime error when resolver returns table

ballerina-tests/tests/36_subscriptions.bal, ballerina-tests/tests/utils.bal, ballerina/constants.bal, ballerina/websocket_service.bal, ballerina/websocket_utils.bal, changelog.md, docs/spec/spec.md
Fixes: [#3548](https://github.com/ballerina-platform/ballerina-standard-library/issues/3548)
=> Fix Socket Connection Gets Closed When the Operation Is Complete or If There Is an Error

ballerina-tests/tests/object_types.bal
=> Fix test hanging with new testerina implementation

ballerina-tests/tests/36_subscriptions.bal, ballerina-tests/tests/test_listeners.bal, ballerina-tests/tests/test_services.bal
Related to: [#3466](https://github.com/ballerina-platform/ballerina-standard-library/issues/3466), [#3579](https://github.com/ballerina-platform/ballerina-standard-library/issues/3579)
=> Add additional test cases to check service doesn't return null for nested service objects

ballerina-tests/tests/03_document_validation.bal, ballerina-tests/tests/resources/documents/invalid_document_having_fragment_with_same_name.graphql, ballerina/engine.bal
=> Fix error not returned for document having same name for fragments

changelog.md, commons/src/main/java/io/ballerina/stdlib/graphql/commons/utils/Utils.java
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3571
N/A
=> Update GraphQL Commons Package APIs

.github/workflows/build-with-bal-test-native.yml, README.md, ballerina-tests/build.gradle, examples/build.gradle, gradle.properties
Related: [#3316](https://github.com/ballerina-platform/ballerina-standard-library/issues/3316)
=> Add workflow for bal test native build

ballerina-tests/tests/01_listener_test.bal, ballerina-tests/tests/test_services.bal, ballerina/listener.bal, changelog.md, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GraphqlSourceModifier.java
$Subject
Fixes: (For 2201.2.x Branch) [#3628](https://github.com/ballerina-platform/ballerina-standard-library/issues/3628)
=> Fix Compilation Failure when Other Annotations are Present

native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/graphql-native/serialization-config.json
$Subject
Fixes: [#3631](https://github.com/ballerina-platform/ballerina-standard-library/issues/3631)
=> Update serialization-config to reflect class path changes

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, ballerina/websocket_service.bal, ballerina/websocket_utils.bal, changelog.md
$Subject
Fixes: [#3661](https://github.com/ballerina-platform/ballerina-standard-library/issues/3661)
=> Close the Stream when it is Completed

ballerina-tests/tests/01_listener_test.bal, ballerina-tests/tests/test_services.bal, changelog.md, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GraphqlSourceModifier.java
$Subject
Fixes: (For 2201.1.x Branch) [#3628](https://github.com/ballerina-platform/ballerina-standard-library/issues/3628)
=> Fix Compilation Error when the Other Annotations are Present

.github/workflows/update-spec.yml, docs/spec/spec.md
$Subject
Fixes: [#3700](https://github.com/ballerina-platform/ballerina-standard-library/issues/3700)
=> Change the Word `Auth` to `Authentication` Where Applicable and Fix Spec Update Workflow

docs/spec/spec.md
Fixes: [#3699](https://github.com/ballerina-platform/ballerina-standard-library/issues/3699)
=> Add spec for interfaces implementing interfaces

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties, native/src/main/java/io/ballerina/stdlib/graphql/runtime/client/QueryExecutor.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ArgumentHandler.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517
=> Fix failing build for type reference support 

load-tests/snowtooth/scripts/snowtooth-test-plan.jmx
=> test load-test from other branch

changelog.md
=> Update the changelog after the 1.5.0 release

README.md
$subject.
Fixes: https://github.com/ballerina-platform/ballerina-central/issues/14
=> Fixes Overview/Service/Mutation Type  example typo

docs/spec/spec.md
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3869
=> Update imperative approach example in spec with interceptors

ballerina/context.bal, changelog.md, docs/spec/spec.md
$Subject
Fixes: [#3709](https://github.com/ballerina-platform/ballerina-standard-library/issues/3709)
Fixes: [#3870](https://github.com/ballerina-platform/ballerina-standard-library/issues/3870)
=> Update the Spec with Input Default Values and Service Error Handling

commons/src/main/java/io/ballerina/stdlib/graphql/commons/utils/SdlSchemaStringGenerator.java, docs/spec/spec.md
Fixes: [#3819](https://github.com/ballerina-platform/ballerina-standard-library/issues/3819)
N/A
=> Add Block String Documentation Generation in SDL Schema Generator

commons/src/main/java/io/ballerina/stdlib/graphql/commons/utils/SdlSchemaStringGenerator.java
Added the changes to make the schema generation consistent across different OSs.
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3920
N/A
=> Update SDL Schema Generator

README.md
=> Fix Typo in Readme File

docs/proposals/sdl-schema-file-generation.md
=> Add SDL Schema File Generation Proposal

ballerina/ping_message_job.bal, ballerina/pong_message_handler_job.bal, ballerina/websocket_service.bal, ballerina/websocket_utils.bal
$Subject
Related to: 
[#3943](https://github.com/ballerina-platform/ballerina-standard-library/issues/3943), [#3942](https://github.com/ballerina-platform/ballerina-standard-library/issues/3942)
=> Unschedule ping, pong handler tasks when client closes the connection

.github/workflows/pull-request.yml
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3988
=> Retry codecov upload on failure

ballerina-tests/tests/36_subscriptions.bal, ballerina-tests/tests/utils.bal
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4009
=> Fix testAlreadyExistingSubscriber failing intermittently

gradle.properties
=> Update the dependency versions to latest timestamps

changelog.md
=> Rearrange changelog entries

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Bump to the Next SNAPSHOT Version

.github/workflows/trigger-load-tests.yml
=> Fix incorrect workflow file

.github/workflows/trigger-load-tests.yml
=> Add missing input in trigger workflow

.github/workflows/trigger-load-tests.yml
=> Fix indentation in trigger-loadtests workflow

native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/graphql-native/serialization-config.json
$Subject
Fix the GraalVM check failure -> https://github.com/ballerina-platform/module-ballerina-graphql/actions/runs/4285698989/jobs/7464319032#step:9:407
Note - Tested out the fixes with the cloned repo and the build was passing.
=> Update serilization config to support newly added classes with serilization

docs/spec/spec.md
Part of: https://github.com/ballerina-platform/module-ballerina-graphql/pull/1229
=> Update graphiql link in spec

codecov.yml
$Subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/4107
N/A
=> [Master] Update CodeCov Path Fix Wildcard

codecov.yml
$Subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/4107
N/A
=> [2201.3.x] Update CodeCov Path Fix Wildcard

compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GraphqlSourceModifier.java
$Subject
Separate issue is not created for this PR since this features is not yet released. Fix is part of: https://github.com/ballerina-platform/module-ballerina-graphql/pull/1229
=> Update compilation error when failing to add service resolver

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> [2201.4.x] Update patch version

gradle.properties
$Subject
Fix for: https://github.com/ballerina-platform/module-ballerina-graphql/actions/runs/4365578120/jobs/7634398606#step:10:863
=> Update dependent module versions

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Update GraphQL Version

.github/workflows/build-timestamped-master.yml, .github/workflows/pull-request.yml, codecov.yml, compiler-plugin-tests/build.gradle, gradle.properties, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/EngineUtils.java
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4195
N/A
=> Add Compiler Plugin Code Coverage to the CodeCov Report

ballerina-tests/tests/27_context.bal, ballerina-tests/tests/36_subscriptions.bal, ballerina/websocket_utils.bal, changelog.md
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4208
=> [Master] Fix subscription payload returned with invalid GraphQL error format

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina-tests/tests/27_context.bal, ballerina-tests/tests/36_subscriptions.bal, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/websocket_utils.bal, changelog.md
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4208
=> [2201.4.x] Fix subscription payload returned with invalid GraphQL error format.

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina-tests/tests/27_context.bal, ballerina-tests/tests/36_subscriptions.bal, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/websocket_utils.bal, changelog.md
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4208
=> [2201.3.x] Fix subscription payload returned with invalid GraphQL error format

README.md, ballerina/Module.md, ballerina/Package.md
=> Fix errors in docs

ballerina/constants.bal, codecov.yml, examples/build.gradle, examples/starwars/modules/datasource/utils.bal, examples/starwars/service.bal, examples/starwars/tests/resources/documents/reviewAdded.graphql, examples/starwars/tests/tests.bal, examples/starwars/tests/utils.bal, examples/starwars/tests/websocket_utils.bal
Fixes: [#4205](https://github.com/ballerina-platform/ballerina-standard-library/issues/4205)
=> Improve Star Wars Example 

ballerina/modules/parser/char_reader.bal, ballerina/modules/parser/lexer.bal, ballerina/modules/parser/parser.bal, ballerina/modules/parser/tests/char_reader_tests.bal, ballerina/modules/parser/tests/lexer_tests.bal, ballerina/modules/parser/utils.bal, examples/starwars/tests/websocket_utils.bal, native/src/main/java/io/ballerina/stdlib/graphql/runtime/parser/ParserUtils.java
$Subject
Fixes: [#4325](https://github.com/ballerina-platform/ballerina-standard-library/issues/4235)
=> Improve the GraphQL Parser to Use `string:Char`

load-tests/book_reviews_mutation/deployment/ingress.yaml, load-tests/book_reviews_mutation/deployment/kustomization.yaml, load-tests/book_reviews_mutation/results/summary.csv, load-tests/book_reviews_mutation/scripts/book-reviews-mutation-test-plan.jmx, load-tests/book_reviews_mutation/scripts/run.sh, load-tests/book_reviews_mutation/src/Ballerina.toml, load-tests/book_reviews_mutation/src/Cloud.toml, load-tests/book_reviews_mutation/src/book.bal, load-tests/book_reviews_mutation/src/modules/datasource/datasource.bal, load-tests/book_reviews_mutation/src/modules/datasource/types.bal, load-tests/book_reviews_mutation/src/modules/datasource/utils.bal, load-tests/book_reviews_mutation/src/review.bal, load-tests/book_reviews_mutation/src/service.bal, load-tests/book_reviews_subscription/deployment/ingress.yaml, load-tests/book_reviews_subscription/deployment/kustomization.yaml, load-tests/book_reviews_subscription/results/summary.csv, load-tests/book_reviews_subscription/scripts/book-reviews-subscription-test-plan.jmx, load-tests/book_reviews_subscription/scripts/pre_run.sh, load-tests/book_reviews_subscription/scripts/run.sh, load-tests/book_reviews_subscription/src/Ballerina.toml, load-tests/book_reviews_subscription/src/Cloud.toml, load-tests/book_reviews_subscription/src/book.bal, load-tests/book_reviews_subscription/src/modules/datasource/datasource.bal, load-tests/book_reviews_subscription/src/modules/datasource/types.bal, load-tests/book_reviews_subscription/src/modules/datasource/utils.bal, load-tests/book_reviews_subscription/src/review.bal, load-tests/book_reviews_subscription/src/service.bal
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3562
=> Add load-test for mutation and subscription

load-tests/book_reviews_mutation/deployment/ingress.yaml, load-tests/book_reviews_subscription/deployment/ingress.yaml
=> Update service name in ingress.yaml

ballerina-tests/tests/test_services.bal, changelog.md, docs/spec/spec.md, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ExecutionCallback.java, spotbugs-exclude.xml
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4237
=> Exit the Listener When Panic Occurred

load-tests/book_reviews_mutation/deployment/ingress.yaml, load-tests/book_reviews_mutation/scripts/book-reviews-mutation-test-plan.jmx, load-tests/book_reviews_mutation/src/book.bal, load-tests/book_reviews_mutation/src/modules/datasource/datasource.bal, load-tests/book_reviews_mutation/src/modules/datasource/types.bal, load-tests/book_reviews_mutation/src/modules/datasource/utils.bal, load-tests/book_reviews_mutation/src/review.bal, load-tests/book_reviews_mutation/src/service.bal, load-tests/book_reviews_subscription/deployment/ingress.yaml, load-tests/book_reviews_subscription/scripts/book-reviews-subscription-test-plan.jmx, load-tests/book_reviews_subscription/src/book.bal, load-tests/book_reviews_subscription/src/modules/datasource/datasource.bal, load-tests/book_reviews_subscription/src/modules/datasource/types.bal, load-tests/book_reviews_subscription/src/modules/datasource/utils.bal, load-tests/book_reviews_subscription/src/review.bal, load-tests/book_reviews_subscription/src/service.bal
=> Remove Aggregate Report listener from test plan files

load-tests/book_reviews_mutation/scripts/book-reviews-mutation-test-plan.jmx, load-tests/book_reviews_subscription/scripts/book-reviews-subscription-test-plan.jmx
=> Remove spaces from json response in test plan files

changelog.md
>$subject
Part of https://github.com/ballerina-platform/module-ballerina-graphql/pull/1297
=> Update the Changelog with Validation Logic Changes

docs/spec/spec.md
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4224
=> Fix markdown rendering issue in table

load-tests/book_reviews_subscription/scripts/post_run.sh
=> Add post_run script to filter WS Next from .jtl

load-tests/book_reviews_mutation/scripts/run.sh, load-tests/book_reviews_subscription/scripts/run.sh
=> set temporary duration

load-tests/book_reviews_mutation/scripts/run.sh, load-tests/book_reviews_subscription/scripts/run.sh, load-tests/snowtooth/scripts/run.sh
=> Set temp values for load-test

load-tests/book_reviews_subscription/scripts/post_run.sh
=> Modify post_run file to print jtl file content

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, load-tests/book_reviews_subscription/scripts/post_run.sh
=> Wait until PR build passes to set correct runtime_artifacts_url

load-tests/book_reviews_subscription/scripts/post_run.sh
=> print tail of jtl file

load-tests/book_reviews_subscription/scripts/post_run.sh
=> fix EOF error

load-tests/book_reviews_subscription/scripts/post_run.sh
=> Add post processing job

load-tests/book_reviews_subscription/scripts/post_run.sh
=> enable FORCE_ENABLE_JMETER_PROCESSING flag

load-tests/book_reviews_subscription/scripts/run.sh
=> reset duration and ramp-up period of subscription load-test

ballerina-tests/Dependencies.toml, ballerina-tests/tests/09_arrays.bal, ballerina-tests/tests/13_tables.bal, ballerina-tests/tests/records.bal, ballerina-tests/tests/resources/documents/arrays_with_errors_in_record_field.graphql, ballerina-tests/tests/resources/documents/resolver_returning_tables_with_errors.graphql, ballerina-tests/tests/resources/expected_results/arrays_with_errors_in_record_field.json, ballerina-tests/tests/resources/expected_results/enum_introspection.json, ballerina-tests/tests/resources/expected_results/interceptors_with_invalid_destructive_modification3.json, ballerina-tests/tests/resources/expected_results/resolver_returning_tables_with_errors.json, ballerina-tests/tests/test_services.bal, ballerina-tests/tests/values.bal, ballerina/Dependencies.toml, ballerina/response_generator.bal, changelog.md
Fixes: [#4286](https://github.com/ballerina-platform/ballerina-standard-library/issues/4286)
=> [2201.4.x] Fix Invalid Path Returning for Errors in Record Fields

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, gradle.properties
=> Update versions for update 5

load-tests/book_reviews_subscription/scripts/pre_run.sh
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4342
=> Update JMeterWebSocketSampler.jar download url

load-tests/book_reviews_mutation/src/Cloud.toml, load-tests/book_reviews_subscription/src/Cloud.toml, load-tests/snowtooth/src/Cloud.toml
=> Increase load test memory

examples/news_alerts/README.md, examples/snowtooth/README.md, examples/starwars/README.md
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/4378
N/A
=> Update Meta Information in Examples

.gitignore, ballerina-tests/Dependencies.toml, ballerina-tests/custom_prefix_without_import.bal, ballerina-tests/services.bal, ballerina-tests/tests/37_interfaces.bal, ballerina/Dependencies.toml, ballerina/build.gradle, changelog.md, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GraphqlSourceModifier.java, gradle.properties, settings.gradle
$Subject
Fixes: [#4364](https://github.com/ballerina-platform/ballerina-standard-library/issues/4364)
Fixes: [#4379](https://github.com/ballerina-platform/ballerina-standard-library/issues/4379)
=> [Master] Fix Issues in Code Modifier with GraphQL Imports 

.gitignore, ballerina-tests/custom_prefix_without_import.bal, ballerina-tests/services.bal, ballerina-tests/tests/37_interfaces.bal, ballerina/build.gradle, changelog.md, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GraphqlSourceModifier.java, gradle.properties, settings.gradle
$Subject
Fixes: [#4364](https://github.com/ballerina-platform/ballerina-standard-library/issues/4364)
Fixes: [#4379](https://github.com/ballerina-platform/ballerina-standard-library/issues/4379)
=> [2201.5.x] Fix Issues in Code Modifier with GraphQL Imports

.gitignore, ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina-tests/custom_prefix_without_import.bal, ballerina-tests/services.bal, ballerina-tests/tests/37_interfaces.bal, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, changelog.md, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GraphqlSourceModifier.java, gradle.properties
$Subject
Fixes: [#4364](https://github.com/ballerina-platform/ballerina-standard-library/issues/4364)
Fixes: [#4379](https://github.com/ballerina-platform/ballerina-standard-library/issues/4379)
=> [2201.4.x] Fix Issues in Code Modifier with GraphQL Imports

ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Revert "Sync Branch After Release 1.6.3"

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Bump the version to the next SNAPSHOT version

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, native/src/main/java/io/ballerina/stdlib/graphql/runtime/client/QueryExecutor.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java
This is to support the build for https://github.com/ballerina-platform/ballerina-standard-library/issues/4344
=> Fix object getType() API usage 

load-tests/book_reviews_mutation/src/Cloud.toml, load-tests/book_reviews_subscription/src/Cloud.toml, load-tests/snowtooth/src/Cloud.toml
Temporarily fix the issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4414
=> Temporarily increase load-test resources

compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GeneratorUtils.java
related issue https://github.com/ballerina-platform/ballerina-standard-library/issues/4419
Fixes:
=> Remove depcrecated `filePath` api and update to `fileName`

ballerina/engine.bal, ballerina/executor_visitor.bal, ballerina/response_generator.bal, changelog.md
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4447
=> Fix non-isolated Function Pointers in Function Calls Within Isolated Functions

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, gradle.properties
=> Update WebSocket to latest timestamp verstion

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, gradle.properties
=> Update the Dependency Versions for SwanLake Update 6

ballerina-tests/tests/interceptors.bal, ballerina-tests/tests/resources/documents/interceptors_with_map.graphql, ballerina-tests/tests/resources/documents/interceptors_with_records.graphql, ballerina-tests/tests/resources/expected_results/interceptors_with_map.json, ballerina-tests/tests/resources/expected_results/interceptors_with_records.json, ballerina/common_utils.bal, ballerina/response_formatter.bal, ballerina/response_generator.bal, changelog.md
Fixes: [#4255](https://github.com/ballerina-platform/ballerina-standard-library/issues/4255)
Fixes: [#4490](https://github.com/ballerina-platform/ballerina-standard-library/issues/4490)
N/A
=> Improve the Return Type Validation in GraphQL Interceptors

ballerina-tests/Dependencies.toml, ballerina-tests/tests/interceptors.bal, ballerina-tests/tests/test_services.bal, ballerina/field.bal
Fixes: [#4504](https://github.com/ballerina-platform/ballerina-standard-library/issues/4504)
N/A
=> Fix Invalid Resource Path Update in `getSubfields` API

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Engine.java
- Stops unnecessary looping after resource or remote method execution
- Introduces minor refactoring changes
=> Improve remote and resource method execution logic in Engine.java

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/ServiceValidationTest.java, compiler-plugin-tests/src/test/resources/ballerina_sources/validator_tests/27_invalid_return_types/service.bal
Fixes: [#4538](https://github.com/ballerina-platform/ballerina-standard-library/issues/4538)
N/A
=> [2201.5.x] Fix Compiler Plugin Test Failure

.github/workflows/build-with-bal-test-graalvm.yml, README.md, ballerina-tests/build.gradle, examples/build.gradle, gradle.properties
$Subject
Related: [#4548](https://github.com/ballerina-platform/ballerina-standard-library/issues/4548)
=> Update Ballerina plugin and change GraalVM flag

ballerina-tests/Dependencies.toml, ballerina-tests/tests/34_graphiql_client.bal, ballerina-tests/tests/utils.bal, ballerina/Dependencies.toml, gradle.properties
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3961
=> Fix test failure due to error structure change in http

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/4568
Fixes:
=> Mark graphql module as GraalVM compatible

docs/proposals/scalar-type-id.md
=> Add proposal for graphql scalar type ID

examples/simple_github_issue_tracker/data_mapper.bal, examples/simple_github_issue_tracker/types.bal
=> Update data mapper code

examples/simple_github_issue_tracker/data_mapper.bal, examples/simple_github_issue_tracker/service.bal, examples/simple_github_issue_tracker/types.bal
=> Update graphql types in Issue Tracker example

examples/simple_github_issue_tracker/data_mapper.bal, examples/simple_github_issue_tracker/service.bal, examples/simple_github_issue_tracker/types.bal
=> Modify branches resource in simple_github_issue_tracker example

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, gradle.properties
=> Update versions for U7

gradle.properties
=> Bump the HTTP version

.github/pull_request_template.md
>$subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/4186
N/A
=> Add Check for 'commons' Package Changes

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, .github/workflows/update-spec.yml, README.md, ballerina/Ballerina.toml, build-config/checkstyle/build.gradle, build-config/resources/Ballerina.toml, gradle.properties, gradle/wrapper/gradle-wrapper.properties, spotbugs-exclude.xml
=> Migrate to Java 17

build.gradle, settings.gradle
=> Disable examples temporary

ballerina/annotations.bal, ballerina/common_utils.bal, ballerina/field_validator_visitor.bal, ballerina/listener.bal, ballerina/records.bal
$title
-<s> [ ] Linked to an issue</s>
-<s> [ ] Updated the changelog</s>
-<s> [ ] Added tests</s>
-<s> [ ] Updated the spec</s>
-<s> [ ] Checked native-image compatibility</s>
=> Fix typos in documentation

docs/spec/spec.md
=> Add GraphQL spec field in the header section

README.md
=> Fix oracle jdk download link

ballerina-tests/tests/34_graphiql_client.bal, ballerina-tests/tests/test_services.bal, ballerina/listener.bal, ballerina/listener_utils.bal, ballerina/types.bal, changelog.md, docs/spec/spec.md
Fixes: [#4585](https://github.com/ballerina-platform/ballerina-standard-library/issues/4586)
Fixes: [#4660](https://github.com/ballerina-platform/ballerina-standard-library/issues/4660)
N/A
=> Print GraphiQL Url to Stdout

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, ballerina/client.bal, ballerina/context.bal, gradle.properties
$Subject
Related to: [#4584](https://github.com/ballerina-platform/ballerina-standard-library/issues/4584)
N/A
=> Fix `isolated` Object Init Methods

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, gradle.properties
=> Remove Lang Timestamp Version

examples/news_alerts/A Guide on GraphQL Subscriptions with Apache Kafka in Ballerina.md, examples/simple_github_issue_tracker/Integrating Multiple Endpoints to Expose as a GraphQL API in Ballerina.md, examples/snowtooth/GraphQL Snowtooth Example with Ballerina.md, examples/starwars/GraphQL Starwars API (SWAPI) in Ballerina.md
This is for SEO purposes so the examples get listed on search engines.
=> Update README files of the examples

ballerina/build.gradle, gradle.properties
=> Make Gradle to do not track incremental builds 

docs/spec/spec.md
=> Move DataLoader to advanced features section in spec

ballerina/executor_visitor.bal
$Subject
Related to: https://github.com/ballerina-platform/ballerina-lang/pull/39585
=> Remove readonly from resolvedResult variable with intersection type API changes

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, docs/spec/spec.md
=> Add a note in spec about prefetch method execution

.github/workflows/build-with-bal-test-graalvm.yml
=> Enable Windows tests for GraalVM check

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/graphql/compiler/ServiceValidationTest.java, gradle.properties
Fixes: [#4672](https://github.com/ballerina-platform/ballerina-standard-library/issues/4672)
N/A
=> Update the GraphQL Compiler Plugin Tests

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, gradle.properties
>$subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/4672
=> Update the Lang Timestamp Version

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, gradle.properties
=> Update java-version to 17.0.7 in workflows

examples/README.md
=> Add a README file for the examples directory

docs/spec/spec.md
=> Add example for list of IDs

.github/pull_request_template.md
=> Update the PR Template

ballerina/listener.bal
>$subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/4586
=> Fix GraphQL Service Url in GraphiQL Client

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml
Part of: https://github.com/ballerina-platform/ballerina-standard-library/issues/4778
=> Migrate workflows to reuse workflows from ballerina-standard-library repo

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml
Part of : https://github.com/ballerina-platform/ballerina-standard-library/pull/4790
=> Set secret to inherit in  Build, Central Publish and Release workflow

.github/workflows/central-publish.yml
=> Fix invalid central publish workflow

.github/workflows/trivy-scan.yml
Part of: https://github.com/ballerina-platform/ballerina-standard-library/issues/4778
=> Migrate trivy workflow to use centralized workflow

README.md, ballerina/Package.md, docs/spec/spec.md, examples/news_alerts/A Guide on GraphQL Subscriptions with Apache Kafka in Ballerina.md, gradle.properties
=> Change Ballerina standard library to Ballerina Library

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina-tests/tests/21_aliases.bal, ballerina-tests/tests/35_client_test.bal, ballerina-tests/tests/object_types.bal, ballerina-tests/tests/resources/documents/alias_on_error_path.graphql, ballerina-tests/tests/resources/expected_results/alias_on_error_path.json, ballerina-tests/tests/resources/expected_results/map_with_invalid_key.json, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/engine_utils.bal, ballerina/response_generator.bal
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4634
=> Use Aliases in GraphQL Error Path

changelog.md
=> Update the changelog after the 1.10.0 release

changelog.md
=> Update the changelog for #4634

.github/workflows/pull-request.yml
=> Inherit Secrets in Pull Request Workflows

changelog.md
=> Update the Changelog

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/constants.bal, ballerina/listener.bal, changelog.md, gradle.properties
Fixes: [#6067](https://github.com/ballerina-platform/ballerina-library/issues/6067)
N/A
=> Fix GraphiQL Client Service Url

.github/workflows/central-publish.yml
=> Fix Central Publish Workflow Issue

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Bump the Dependency Versions

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, ballerina/modules/dataloader/dataloader.bal, changelog.md, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/diagnostics/DiagnosticMessage.java, compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/schema/generator/GraphqlSourceModifier.java
$Subject
Fixes: [#6418](https://github.com/ballerina-platform/ballerina-library/issues/6418)
Fixes: [#6310](https://github.com/ballerina-platform/ballerina-library/issues/6310)
N/A
=> Fix Code Coverage Showing Invalid Values with GraphQL Compiler Plugin

.github/workflows/build-timestamped-master.yml, .github/workflows/build-with-bal-test-graalvm.yml, .github/workflows/central-publish.yml, .github/workflows/process-load-test-result.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trigger-load-tests.yml, .github/workflows/trivy-scan.yml
=> Update the workflow template links

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, ballerina/constants.bal, ballerina/engine.bal, ballerina/engine_utils.bal, ballerina/init.bal, ballerina/listener_utils.bal, ballerina/response_formatter.bal, changelog.md, docs/spec/spec.md
Fixes: [#6461](https://github.com/ballerina-platform/ballerina-library/issues/6461)
=> Adding Support for GraphQL Observability Metrics

ballerina/engine.bal, ballerina/engine_utils.bal, ballerina/init.bal, ballerina/response_formatter.bal
=> Check Metrics Enabled Before Adding Tags

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/engine.bal, ballerina/engine_utils.bal, ballerina/field.bal, ballerina/observe_utils.bal, ballerina/response_generator.bal, ballerina/tests/08_get_subfields.bal, ballerina/tests/09_cache_utils.bal, ballerina/tests/field_object_types.bal, ballerina/tests/utils.bal, build-config/resources/BallerinaTest.toml
=> Update the field name for observability metrics

compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/service/validator/ServiceValidator.java
=> Exclude the `WARNING_210` diagnostic from using the type symbol's location

ballerina/engine.bal, ballerina/tests/06_configurations_test.bal, ballerina/tests/service.bal, docs/spec/spec.md
=> Validate the Max Query Complexity Value

README.md, ballerina/Module.md, ballerina/Package.md
=> Fix incorrect code in README files

docs/spec/spec.md
=> Improve Spec to Reduce Ambiguity in Interface Types

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, gradle.properties
=> Bump the Dependencies for Update 10 Release

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, gradle.properties
=> Bump the Dependencies of JWT and Others for Update 10

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, ballerina/engine.bal, ballerina/tests/06_configurations_test.bal, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/meta/Resource.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/meta/ServiceAnalyzer.java
=> Validate the Default Field Complexity and Field Complexity Values

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina-tests/build.gradle, ballerina-tests/tests/01_listener_test.bal, ballerina-tests/tests/27_context.bal, ballerina-tests/tests/41_dataloader.bal, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml
Related to: https://github.com/ballerina-platform/ballerina-library/issues/7030
=> Temporarily disable subscription tests

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, ballerina/context.bal, ballerina/engine.bal, ballerina/engine_utils.bal, ballerina/executor_visitor.bal, ballerina/field.bal, ballerina/modules/parser/operation_node.bal, ballerina/response_generator.bal, ballerina/tests/utils.bal, ballerina/value_tree_builder.bal, changelog.md, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Context.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ExecutorVisitor.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ListenerUtils.java
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/4122
=> [2201.9.x] Introduce Parallel Execution for the GraphQL Resolvers

.gitignore, ballerina-tests/graphql-advanced-test-suite/Dependencies.toml, ballerina-tests/graphql-client-test-suite/Dependencies.toml, ballerina-tests/graphql-dataloader-test-suite/Dependencies.toml, ballerina-tests/graphql-interceptor-test-suite/Dependencies.toml, ballerina-tests/graphql-security-test-suite/Dependencies.toml, ballerina-tests/graphql-service-test-suite/Dependencies.toml, ballerina-tests/graphql-subgraph-test-suite/Dependencies.toml, ballerina-tests/graphql-subgraph-test-suite/tests/resources/expected_results/input_object_with_unexpected_variable_fields1.json, ballerina-tests/graphql-subgraph-test-suite/tests/resources/expected_results/input_object_with_unexpected_variable_fields2.json, ballerina-tests/graphql-subscription-test-suite/Dependencies.toml, ballerina-tests/graphql-test-common/Dependencies.toml, ballerina/Dependencies.toml, ballerina/context.bal, ballerina/engine.bal, ballerina/engine_utils.bal, ballerina/executor_visitor.bal, ballerina/field.bal, ballerina/modules/parser/operation_node.bal, ballerina/response_generator.bal, ballerina/tests/utils.bal, ballerina/value_tree_builder.bal, changelog.md, gradle.properties, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/Context.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ExecutorVisitor.java, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ListenerUtils.java
Fixes: [#7317](https://github.com/ballerina-platform/ballerina-library/issues/7317)
Fixes: [#4122](https://github.com/ballerina-platform/ballerina-library/issues/4122)
=> Introduce Parallel Execution for the GraphQL Resolvers

ballerina-tests/graphql-dataloader-test-suite/Dependencies.toml, ballerina-tests/graphql-dataloader-test-suite/tests/01_dataloader_tests.bal, ballerina-tests/graphql-dataloader-test-suite/tests/02_dataloader_with_server_cache.bal
This PR will help to identify the failing test case : https://github.com/ballerina-platform/ballerina-lang/actions/runs/12192685558/job/34017092795?pr=43689
=> Add print statements in dataloader tests

.github/workflows/build-timestamped-master.yml, .github/workflows/pull-request.yml, ballerina-tests/graphql-dataloader-test-suite/tests/01_dataloader_tests.bal, ballerina-tests/graphql-service-test-suite/tests/30_graphiql_client.bal, ballerina-tests/graphql-subscription-test-suite/modules/five/tests/01_subscription_five_tests.bal, ballerina-tests/graphql-subscription-test-suite/modules/five/tests/02_subscription_with_context.bal, ballerina-tests/graphql-subscription-test-suite/modules/five/tests/03_subscription_with_constraint.bal, ballerina-tests/graphql-subscription-test-suite/modules/four/tests/01_subscription_four_tests.bal, ballerina-tests/graphql-subscription-test-suite/modules/one/tests/01_subscription_tests.bal, ballerina-tests/graphql-subscription-test-suite/modules/six/tests/01_subscription_six_tests.bal, ballerina-tests/graphql-subscription-test-suite/modules/six/tests/01_subscription_with_interceptors.bal, ballerina-tests/graphql-subscription-test-suite/modules/three/tests/01_subscription_three_tests.bal, ballerina-tests/graphql-subscription-test-suite/modules/two/tests/01_subscription_two_tests.bal, ballerina/tests/03_subscriptions.bal
=> Reenanble tests in code and disable from workflow

ballerina-tests/graphql-dataloader-test-suite/tests/01_dataloader_tests.bal
=> Add missing test dependency

.github/workflows/build-timestamped-master.yml, .github/workflows/pull-request.yml
=> Reenable tests in workflow

native/src/main/java/io/ballerina/stdlib/graphql/runtime/utils/Utils.java, native/src/main/java/module-info.java, spotbugs-exclude.xml
=> Add dump thread logic temporary

ballerina-tests/graphql-advanced-test-suite/Dependencies.toml, ballerina-tests/graphql-client-test-suite/Dependencies.toml, ballerina-tests/graphql-dataloader-test-suite/Dependencies.toml, ballerina-tests/graphql-interceptor-test-suite/Dependencies.toml, ballerina-tests/graphql-security-test-suite/Dependencies.toml, ballerina-tests/graphql-service-test-suite/Dependencies.toml, ballerina-tests/graphql-subgraph-test-suite/Dependencies.toml, ballerina-tests/graphql-subscription-test-suite/Dependencies.toml, ballerina-tests/graphql-test-common/Dependencies.toml, native/src/main/java/io/ballerina/stdlib/graphql/runtime/utils/Utils.java, native/src/main/java/module-info.java
=> Modify dump logic

native/src/main/java/io/ballerina/stdlib/graphql/runtime/utils/Utils.java
=> Check server up

native/src/main/java/io/ballerina/stdlib/graphql/runtime/utils/Utils.java
=> Replace with thread pool

native/src/main/java/io/ballerina/stdlib/graphql/runtime/utils/Utils.java
=> Fix checkstyle

ballerina-tests/build.gradle
Related to https://github.com/ballerina-platform/ballerina-library/issues/7529
=> Disable subscription tests on Ubuntu

ballerina-tests/graphql-advanced-test-suite/Dependencies.toml, ballerina-tests/graphql-client-test-suite/Dependencies.toml, ballerina-tests/graphql-dataloader-test-suite/Dependencies.toml, ballerina-tests/graphql-interceptor-test-suite/Dependencies.toml, ballerina-tests/graphql-security-test-suite/Dependencies.toml, ballerina-tests/graphql-service-test-suite/Dependencies.toml, ballerina-tests/graphql-subgraph-test-suite/Dependencies.toml, ballerina-tests/graphql-test-common/Dependencies.toml, ballerina/Dependencies.toml, gradle.properties
=> Update library timstamped versions

ballerina-tests/build.gradle, ballerina-tests/graphql-advanced-test-suite/Dependencies.toml, ballerina-tests/graphql-client-test-suite/Dependencies.toml, ballerina-tests/graphql-dataloader-test-suite/Dependencies.toml, ballerina-tests/graphql-interceptor-test-suite/Dependencies.toml, ballerina-tests/graphql-security-test-suite/Dependencies.toml, ballerina-tests/graphql-service-test-suite/Dependencies.toml, ballerina-tests/graphql-subgraph-test-suite/Dependencies.toml, ballerina-tests/graphql-test-common/Dependencies.toml, ballerina/Dependencies.toml
=> Fix Release Build Failure due to Dependencies.toml Being deleted.

ballerina-tests/build.gradle
=> Avoid deleting Dependencies.toml file when cleaning

changelog.md, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ListenerUtils.java, native/src/main/resources/graphiql.html
Part of [#7614](https://github.com/ballerina-platform/ballerina-library/issues/7614)
=> [2201.10.x] Fix Broken GraphiQL Client

changelog.md, native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/ListenerUtils.java, native/src/main/resources/graphiql.html
Fixes: [#7614](https://github.com/ballerina-platform/ballerina-library/issues/7614)
=> [master] Fix Broken GraphiQL Client

ballerina-tests/tests/27_context.bal
Related to https://github.com/ballerina-platform/ballerina-library/issues/7529
=> [2201.10.x] Disabling the Hanging Tests in GraphQL Package
